apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-basic-auth
  namespace: argocd
spec:
  basicAuth:
    secret: cloudflare-basic-auth
    realm: geron
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-cloudflare-auth
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`vasary.org`) && HeaderRegexp(`Cf-Ray`, `.+`)
      kind: Rule
      priority: 100000
      middlewares:
        - name: cloudflare-basic-auth
          namespace: argocd
      services:
        - name: argocd-server
          port: http
  tls:
    secretName: argocd-vasary-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-cloudflare-auth-web
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vasary.org`) && HeaderRegexp(`Cf-Ray`, `.+`)
      kind: Rule
      priority: 100000
      middlewares:
        - name: cloudflare-basic-auth
          namespace: argocd
      services:
        - name: argocd-server
          port: http
