apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-authentik-auth
  namespace: monitoring
spec:
  forwardAuth:
    address: http://authentik-server.authentik.svc.cluster.vasary.org/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-Authentik-Username
      - X-Authentik-Groups
      - X-Authentik-Email
      - X-Authentik-Name
      - X-Authentik-Uid
