apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - coins-inventory.yaml
  - echo-server.yaml
  - immich.yaml
  - jellyfin.yaml
  - outline.yaml
  - paperless.yaml
  - seafile.yaml
  - stirling-pdf.yaml
  - vaultwarden.yaml
