apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-redis-data-local
  namespace: outline
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
