apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data
  namespace: outline
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
