apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - local-path-storage.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - nfs-csi.yaml
  - reloader.yaml
  - traefik.yaml
