apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-runners.yaml
  - arc-systems.yaml
  - cert-manager.yaml
  - cloudflared.yaml
  - cnpg-system.yaml
  - echo-server.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - local-path-storage.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - nfs-csi.yaml
  - redis-operator.yaml
  - reloader.yaml
  - traefik.yaml
