apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-runners.yaml
  - arc-systems.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cloudflared.yaml
  - cnpg-system.yaml
  - coins-inventory.yaml
  - echo-server.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - homepage.yaml
  - immich.yaml
  - librechat.yaml
  - llm-proxy.yaml
  - local-path-storage.yaml
  - mariadb-operator.yaml
  - media.yaml
  - mcp.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - nfs-csi.yaml
  - outline.yaml
  - paperless.yaml
  - redis-operator.yaml
  - reloader.yaml
  - seafile.yaml
  - stirling-pdf.yaml
  - traefik.yaml
  - vaultwarden.yaml
