apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo-server-cloudflare-auth
  namespace: echo-server
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`echo.vasary.org`) && HeaderRegexp(`Cf-Ray`, `.+`)
      kind: Rule
      priority: 100000
      middlewares:
        - name: cloudflare-authentik-auth
          namespace: echo-server
      services:
        - name: echo-server
          port: 80
  tls:
    secretName: echo-vasary-tls
