apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - echo-server-cloudflare-authentik-auth.yaml
  - echo-server-cloudflare-auth.yaml
  - echo-server-cloudflare-auth-web.yaml
  - cloudflare-authentik-auth.yaml
  - prometheus-cloudflare-auth.yaml
  - prometheus-cloudflare-auth-web.yaml
