apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-secrets
  storage:
    storageClass: nfs
    size: 20Gi
