apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-blueprint.yaml
  - database.yaml
  - grafana-blueprint.yaml
  - immich-blueprint.yaml
  - jellyfin-blueprint.yaml
  - outline-blueprint.yaml
  - redis.yaml
  - seafile-blueprint.yaml
  - stirling-pdf-blueprint.yaml
