apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-navidrome
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprint
    blueprints.goauthentik.io/instantiate: "true"
data:
  navidrome.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: vasary-navidrome-proxy
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_core.group
        id: navidrome-users-group
        state: present
        identifiers:
          name: navidrome-users
        attrs:
          name: navidrome-users
      - model: authentik_core.group
        id: seasonvar-users-group
        state: present
        identifiers:
          name: seasonvar-users
        attrs:
          name: seasonvar-users
      - model: authentik_core.group
        id: public-cloudflare-users-group
        state: present
        identifiers:
          name: public-cloudflare-users
        attrs:
          name: public-cloudflare-users
      - model: authentik_providers_proxy.proxyprovider
        id: navidrome-proxy-provider
        state: present
        identifiers:
          name: navidrome
        attrs:
          name: navidrome
          mode: forward_single
          external_host: https://navidrome.vasary.org
          internal_host: http://navidrome.media.svc.cluster.vasary.org
          internal_host_ssl_validation: false
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
      - model: authentik_providers_proxy.proxyprovider
        id: seasonvar-proxy-provider
        state: present
        identifiers:
          name: seasonvar
        attrs:
          name: seasonvar
          mode: forward_single
          external_host: https://seasonvar.vasary.org
          internal_host: http://seasonvar.media.svc.cluster.vasary.org
          internal_host_ssl_validation: false
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
      - model: authentik_providers_proxy.proxyprovider
        id: echo-public-proxy-provider
        state: present
        identifiers:
          name: echo-public
        attrs:
          name: echo-public
          mode: forward_single
          external_host: https://echo.vasary.org
          internal_host: http://echo-server.echo-server.svc.cluster.vasary.org
          internal_host_ssl_validation: false
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
      - model: authentik_providers_proxy.proxyprovider
        id: prometheus-public-proxy-provider
        state: present
        identifiers:
          name: prometheus-public
        attrs:
          name: prometheus-public
          mode: forward_single
          external_host: https://prometheus.vasary.org
          internal_host: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.vasary.org:9090
          internal_host_ssl_validation: false
          authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
      - model: authentik_core.application
        id: navidrome-application
        state: present
        identifiers:
          slug: navidrome
        attrs:
          name: Navidrome
          slug: navidrome
          provider: !KeyOf navidrome-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://navidrome.vasary.org/
          open_in_new_tab: true
      - model: authentik_core.application
        id: seasonvar-application
        state: present
        identifiers:
          slug: seasonvar
        attrs:
          name: Seasonvar
          slug: seasonvar
          provider: !KeyOf seasonvar-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://seasonvar.vasary.org/
          open_in_new_tab: true
      - model: authentik_core.application
        id: echo-public-application
        state: present
        identifiers:
          slug: echo-public
        attrs:
          name: Echo Public Gate
          slug: echo-public
          provider: !KeyOf echo-public-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://echo.vasary.org/
          open_in_new_tab: true
      - model: authentik_core.application
        id: prometheus-public-application
        state: present
        identifiers:
          slug: prometheus-public
        attrs:
          name: Prometheus Public Gate
          slug: prometheus-public
          provider: !KeyOf prometheus-public-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://prometheus.vasary.org/
          open_in_new_tab: true
      - model: authentik_policies.policybinding
        id: navidrome-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf navidrome-application
          group: !KeyOf navidrome-users-group
          order: 0
        attrs:
          target: !KeyOf navidrome-application
          group: !KeyOf navidrome-users-group
          order: 0
      - model: authentik_policies.policybinding
        id: seasonvar-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf seasonvar-application
          group: !KeyOf seasonvar-users-group
          order: 0
        attrs:
          target: !KeyOf seasonvar-application
          group: !KeyOf seasonvar-users-group
          order: 0
      - model: authentik_policies.policybinding
        id: seasonvar-public-cloudflare-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf seasonvar-application
          group: !KeyOf public-cloudflare-users-group
          order: 1
        attrs:
          target: !KeyOf seasonvar-application
          group: !KeyOf public-cloudflare-users-group
          order: 1
      - model: authentik_policies.policybinding
        id: echo-public-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf echo-public-application
          group: !KeyOf public-cloudflare-users-group
          order: 0
        attrs:
          target: !KeyOf echo-public-application
          group: !KeyOf public-cloudflare-users-group
          order: 0
      - model: authentik_policies.policybinding
        id: prometheus-public-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf prometheus-public-application
          group: !KeyOf public-cloudflare-users-group
          order: 0
        attrs:
          target: !KeyOf prometheus-public-application
          group: !KeyOf public-cloudflare-users-group
          order: 0
      - model: authentik_outposts.outpost
        id: embedded-outpost
        state: present
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          providers:
            - !KeyOf navidrome-proxy-provider
            - !KeyOf seasonvar-proxy-provider
            - !KeyOf echo-public-proxy-provider
            - !KeyOf prometheus-public-proxy-provider
