apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-openproject
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprint
    blueprints.goauthentik.io/instantiate: "true"
data:
  openproject.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: vasary-openproject-oauth
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_core.group
        id: openproject-users-group
        state: present
        identifiers:
          name: openproject-users
        attrs:
          name: openproject-users
      - model: authentik_providers_oauth2.oauth2provider
        id: openproject-oauth-provider
        state: present
        identifiers:
          name: openproject
        attrs:
          name: openproject
          client_type: confidential
          client_id: openproject
          client_secret: !Env [OPENPROJECT_OAUTH_CLIENT_SECRET, ""]
          grant_types:
            - authorization_code
            - refresh_token
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-explicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
          redirect_uris:
            - matching_mode: strict
              url: https://openproject.vasary.org/auth/authentik/callback
            - matching_mode: strict
              url: https://openproject.vasary.org/auth/oidc-authentik/callback
          sub_mode: user_email
          issuer_mode: per_provider
      - model: authentik_core.application
        id: openproject-application
        state: present
        identifiers:
          slug: openproject
        attrs:
          name: OpenProject
          slug: openproject
          provider: !KeyOf openproject-oauth-provider
          policy_engine_mode: any
          meta_launch_url: https://openproject.vasary.org/
          open_in_new_tab: true
      - model: authentik_policies.policybinding
        id: openproject-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf openproject-application
          group: !KeyOf openproject-users-group
          order: 0
        attrs:
          target: !KeyOf openproject-application
          group: !KeyOf openproject-users-group
          order: 0
