apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-data
  namespace: authentik
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
