apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components/sftp-backup-uploader
  - ../components/deployment-history-limit
resources:
  - config.yaml
  - database.yaml
  - deployment.yaml
  - postgres-backup.yaml
  - service.yaml
  - ingress.yaml
