apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-mariadb-data-local
  namespace: seafile
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
