apiVersion: v1
kind: ConfigMap
metadata:
  name: seafile-mariadb-init
  namespace: seafile
data:
  01-seafile-databases.sh: '#!/bin/sh

    set -eu


    mariadb -uroot -p"${MARIADB_ROOT_PASSWORD}" <<EOSQL

    CREATE DATABASE IF NOT EXISTS ccnet_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    CREATE DATABASE IF NOT EXISTS seafile_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    CREATE DATABASE IF NOT EXISTS seahub_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    CREATE USER IF NOT EXISTS ''seafile''@''%'' IDENTIFIED BY ''${SEAFILE_MYSQL_DB_PASSWORD}'';

    ALTER USER ''seafile''@''%'' IDENTIFIED BY ''${SEAFILE_MYSQL_DB_PASSWORD}'';

    GRANT ALL PRIVILEGES ON ccnet_db.* TO ''seafile''@''%'';

    GRANT ALL PRIVILEGES ON seafile_db.* TO ''seafile''@''%'';

    GRANT ALL PRIVILEGES ON seahub_db.* TO ''seafile''@''%'';

    FLUSH PRIVILEGES;

    EOSQL

    '
