apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oauth-config.yaml
  - database-storage.yaml
  - database-config.yaml
  - database-workload.yaml
  - redis-storage.yaml
  - redis-workload.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
