apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: seafile
  namespace: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  mariaDbRef:
    name: seafile-mariadb
    waitForIt: true
  name: seafile
  host: "%"
  maxUserConnections: 100
  passwordSecretKeyRef:
    name: seafile-secrets
    key: SEAFILE_MYSQL_DB_PASSWORD
  cleanupPolicy: Skip
