apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: seafile
  namespace: seafile
spec:
  mariaDbRef:
    name: seafile-mariadb
  name: seafile
  host: "%"
  passwordSecretKeyRef:
    name: seafile-secrets
    key: SEAFILE_MYSQL_DB_PASSWORD
  cleanupPolicy: Skip
