apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-shared
  namespace: seafile
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
