apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../platform/components/deployment-history-limit
resources:
  - config.yaml
  - rbac.yaml
  - workload.yaml
  - ingress.yaml
