apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - jellyfin-storage.yaml
  - jellyfin-workload.yaml
  - seasonvar-storage.yaml
  - seasonvar-workload.yaml
  - seasonvar-jobs.yaml
  - seasonvar-routing.yaml
