apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner-nvme
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  source:
    repoURL: https://charts.containeroo.ch
    chart: local-path-provisioner
    targetRevision: 0.0.38
    helm:
      releaseName: local-path-provisioner-nvme
      values: |
        storageClass:
          create: true
          name: local-path-nvme
          defaultClass: false
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /var/mnt/local-path-nvme
        configmap:
          name: local-path-config-nvme
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
