apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:liyIviima2767BZYEbBPOewCvArjwmogpBBnGlirqlJJ/qTSazqk8+ar2VRCaynToBYSTokG3l7HY6tS,iv:+OaFjlO1LYT1YElHLt2OBZ5HFFXN3CFzSEM50BXFiYw=,tag:AlleNHCXKc8SI5zIS7TLYQ==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:CnRw/+onhhfl2qMBqy2Dhy9Wz20=,iv:SaL1Co1UXrVLava1ofK6tYoK/DqQ4SGbvJvVKH2O0oE=,tag:jkhxiLc2Bso7brjBYw/X3A==,type:str]
    dex.authentik.clientSecret: ENC[AES256_GCM,data:gBQ+ojuGa9S4sarAWAEFINdM7eHgtcFO1RLaCrhwRhZJJym7UpyRV7tlhDlKEaob7cUo/14md30DRW8wprGPIA==,iv:fppmtk+epFqoycWbAgUswYj68RvrOH5yeLas8Og92N4=,tag:IJwXz5NElSSjfQ1VArmU5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2b0w3QkMxSlNPYWxsdDhk
            cC9nbk13akxaRkI2RXYzZDlITnI4UEVHNXpRClYzd0xZWUljcVN6MEd3c29Fczdz
            SUcyOGxydTNmNmVyOXFtMDN5TFp0QW8KLS0tIEluLzN2QUg0bkJjdmF5cW5TRGEv
            WGdFcklEWlZEWEwwYWEwUldSd20xem8Kn+brDUhgaIpNNbmaKdJKCBKJ6L+CaM1H
            ZQVFpmbV/mqZ4Ij3WDcOE/A5cVgLh+/2eKkRm2GT4rqoryZXJ4rXXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T19:30:15Z"
    mac: ENC[AES256_GCM,data:bzL2fxmR8eCSvM+p77X+4XGwzlnGbYQGFhOJPZSHoBxUMIiZE37BZQ/CBYyuAVpN6Cde6F3U4qr/AvcWYtnQqRCQv+lfgFKAFBe6FpW87WWkiay4AMAWf8wbelDCulxYoZR9+nfXw2lNmXNFMMSGwXS3LMfS+tXK1m6uecQUFmc=,iv:8FbE3ilI9VciPIZR+z1RWS2N0udDq7rZMQV2fyWPbfU=,tag:gSwC46HTGcwhC4fm7P8rRQ==,type:str]
    version: 3.13.2
