apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:pXKI30MKo+pN,iv:zMROMEatrwZKsIlbB+d/6MGP42sz0KJjZt/vfFxVbf4=,tag:uXyuaD52S7qqwowjR9e2mg==,type:str]
    password: ENC[AES256_GCM,data:J7viwwG/2Ax8qJiFv42+vE6ogaw80hWoVFjicfQdBGJZpJ+jrz6t9c5ApMgzsG3e,iv:TEo6bmYvuL4rZhR2rdYSQdnPuAinfz5ZGj/vVRtwcwc=,tag:RtyOcwHNGk5zxiuhrBGInw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:vlX0VTT1+qaXEMXSqJZQDiE2Ir14xxVlnX33W1Y5BK7ESmDIk3j13LbC2+Qyx2R8dD98NIc0N/drBGPR0UBNRK/YcRfVait8GosgukQ1NLA=,iv:ejj+3mTfl1hGLwHhLirU9AZtJ1JayhwEnGv2iVca+e8=,tag:kARXenRSrHBwlN6NOyiVmg==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:fHf1lB0=,iv:N6DwW200IM/y4hnRFujlymBO/TRtjLCxRtAO6qZPX+Y=,tag:Wt5EzH7VodYmJ5uItQm2hg==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:WERi5qyeHo61w/ww37s/Wy3Dq1Va,iv:F0Q/qBgX2TfAk52v0MxD8WZLy0ZaQRH4H6MR2ukUj5k=,tag:QLUj+KFUST8VB8b+HnosPQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:mf1vYPVWGbn4,iv:ky7Z8rnwvOcbOnwTCSj6WW7NZCwlEJhr5ZayELQT7RE=,tag:1TmYyPIHeXUqWJw8Dfe9Eg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:WPp3ThLqDhXC,iv:6uqAAKn2vlNDyLcZ6k6BB1S1xdsq+LMzF23FY6sRoiI=,tag:C1NcbtP/ISyQuL/kuFSfsw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:CtdNx1F2nPp4N4yDqyUCytnvwZ24KLA7bVQy7afh82aU6VxGvT9NNSb+CJQ7k1ZZ,iv:YUSYLN7/yGx0zfj/tQcswGqnewEXFe2lPjRpUR/Ktm4=,tag:nJrhnBhsw/nExun4ixVuEg==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:FZZt0UvUa2PuOSnVWoga,iv:oCahdrrjbdKxU721UW7aPQIO2jwOjutXKbVAfh2X4PA=,tag:LMnR+atDXj92BLDrNvDQ1A==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:VbiUWZeunsk859EAi27moA==,iv:ju+k+XZ0ZD7QvDftIcqT2b2Tz4T1pVhS5gC/tGjX/dM=,tag:EqROXqFD3KVQxTHAINIoxQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Z4PBoajDDfuT231rOrh4QQ4RmZkP2wRSMKaSXAUudUAMx0y88Pdhrky7azdq9+GMxu61GY+QvYzB8asdFJ62QQ==,iv:g40ZMsTEHyy7bRfl5Yvj/WbQv8XRYV/p1vtiXDehLv8=,tag:9+RBXEY266CC6Ip39KWWrA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:EWyztSpsyqYK0EnK7HKrYTgH0XU5VgRxWBS4QB6I+rFKmcCJlFjhIrzY05pIA2hb,iv:Jkhm2DNdOZu97LLCPqBGFkhW+cXVaWYR5BP+GDGpTgU=,tag:lQngFfHQ4X5Swfqeno+qNA==,type:str]
    SEAFILE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fkpXUuo4kxUpFMJbH+09c/aA91hy6jlumLM/wwrh804+FcZDDodHsvkUcgyw6V8wrzIfeX2cKSBku6omgqQImQ==,iv:AEafQXjz6ywuYOHW8pcIx9vZRENyzjLTraz6SsdoH2Y=,tag:oaOCWVYASrrwOsgIJOJZkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL2NtNElldEl6VkpHcHB6
            cjdjd1czTDk4c2swNEtCVnBPVjhOTzRocW4wCitNTjZxcWM5d3p1ZzVpUDFvelJr
            NHVTczQwL2xueXNsZkhmMWJId2RPRk0KLS0tIGN5L3BLRWN5K05xQ1daY0VZTXdN
            Qmp4b3NDcS92TzBHQ2d1cXgxVWNXcEUKGJ7+PaQcKTmRkkhqZZQhLdUTSjCkhfuj
            KFzi5pgqgKl6j0PJFt1HhJsPPoGnlA0gD3TpbkxVXlQI88Uj6HiiFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T16:39:46Z"
    mac: ENC[AES256_GCM,data:a7j3skYlUTS4be1JSPYnmAgbtlaTakK/MIDilhWbfbGAm/j1jv5Hs0jmLpnJzY3fLHS4mkBCvWaL14hSY5gHYMDy8INPTrXXvvGchi6NBbKMOdNku7Zjq3GAnqoZd6go8Pc4wr7kfL1mhSFz1ubal8Pk9urDu5QtNE6MPYYPNK4=,iv:C+CLr4/R78OQ41nzHWrRaJ9G72gRIqCo/yyFW2S4x2w=,tag:Cr+sric4QcN9rSf5hgh6LA==,type:str]
    version: 3.13.2
