apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rXvPbd7l9le7,iv:+hPERWtlpsadxQru4xcc1sg41r1AyNn870iph3d6+Q4=,tag:QAB6s27QWAXMPJXXNgeEdg==,type:str]
    password: ENC[AES256_GCM,data:JhuuRFoH2oBnMPMdM8tYMU3Y+pkAogMtFAC/HwlqeCNVduWRwzYkWnB1Qxxjr6YE,iv:Cj2T6Y+GFjV5FGe/w26ZM9Zn7YDGLXv7+umhyWGgm/g=,tag:cZROq6NdZJM3i/OtdnvOEw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:2NHutQ4TYlPzTz7OL5wnnC4dtRo1fcUIfsRK6zfBA1ReWLH02bSCOUqDIPB8qaM8H0ErLBYWEky9jv+MgiUQZYOkDcnjEuEjxjjXT6q8ZZg=,iv:LWShuvM5+GsnUDvYpc8YbDuSa42KboXFsAbQ7siqKDs=,tag:XgAIxtCiwJB0eExB2VRNWg==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:Ame8lmA=,iv:VdK9YM49naoy9eEHNon2kaPQ9d1rqhLueWllC00Tjfc=,tag:jtzv54gJHxv27Hphn+Y/FA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:9NKfCEsesYPsrJeCEVOwbv/mn83j,iv:7f3zE5AuFB1Blc0GZfa5mErXYEPDVZ5h8HKFmLTDVYM=,tag:Ldc8ZMZjEZqV+69AY6DNfA==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:FslDp0B1ODA+,iv:PYG7+l4qAZjDN6TPayi2uoCqTtdVh3ggwsL/6jVrts8=,tag:oo1ypjjkxQM+fKZj85zEBA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:eIIbf/clnSnH,iv:OXpB8Zp/yBUO1XZUrYz7ZxF67y/HamFXZC6AHwh8j3M=,tag:gKcA8udaoxtm7b8rZJ9kqw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:I+d9pUnyFaqAVc3cysqEqEnS3ekG5cGMu41kww4LLqwzxd3SdGRomBo5UGi4qiyA,iv:XalmCAR3lpZpxsCovxZ+tmWf8q0JUJEP61rFBLZQR7s=,tag:jY3AHgbMhb9KmXjE3t+s2g==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:6jbdbNzFazcOP2R5lTvA,iv:tBHXRdgGxLx4dHc6gn0LuZbqleYsI8RTSQ+nBS907uY=,tag:uxe6xSNw/HperhGVI3uRmg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:CzoGRUFLpnNdXNe8bc9tvQ==,iv:csvaM+VsR6GNLWeW4vV0xGU2BlppyIgy9p0SJDQ1JGk=,tag:1PD6NF2Cc8olZeBGku9cjQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:JhZU8gsejxI7aRCMdlp4yxFZkkdluWmKqaQEONVhf6CZ/iKTXcWrKOXnz4L8L3/hNaEYve2v/15y4V1hJMEYiw==,iv:Z4Kg6DI0FftpFl6JEVTeuPp8V41Ao82oTI+aBBMGALQ=,tag:xXPNGZKPDHYdRsqVSw13cQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:wd2GT5Beiv5TaTypEGaoab99I5Qb3HHZCJg6MVyfTh1nfEusOvGGIgL8CLSx+Oa7,iv:9t4ksJ2HQkaoxHcxwNWlln/L7GXAhrLzZL2rXCfYjyw=,tag:GGv2G3OIS+bqWAzidRiSPA==,type:str]
    SEAFILE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QWWPt3WI0wl3F+F/lCdBf2uB10HCwO/g4dSSM3ANhme/ijUcr0yrbhx3bZTQEEMFJXOR0Y+V+a2x3OmbQ/xORg==,iv:l9Fm9/2XyTrM85feldFQJEYWynuqsIP10dUrG/Q/bZQ=,tag:bbDS36QQKaZrwYPyRNrvZA==,type:str]
    IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lGN/bUR3exwzsuFqp8q7V8wyNIAz2QjUUTKp2DIqcWm3cyqnb+djaKXi5d6NC5kcHJEXPVvJIVSF3v4vtRMMdt6Pm1DC9iscGnuJ7ok1iMjlIGqeAKLCePkV6saAHqmv,iv:OHy51A3ZWX1YnHhztNHsXHH2xUyJveFEgJO7pL2WEZc=,tag:ZKAzsepLUPFUKfNGjGkUtg==,type:str]
    ARGOCD_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:pGqD3Q8ZfGBVOhqqXmxmHtVue8OSmwduqTPO56DMSacOKsaY7ikxCfTf8hOndEv2yCbJOWI589fgto8Il8GFig==,iv:Jm2zw9mo/Ib8du4TkDDjRCwotIccyKtzHjA8h4AAlRQ=,tag:ERND2fNLCLQ84n6O1sWKNg==,type:str]
    STIRLING_PDF_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IfgPZ5zma3DZSd+Od38R8AjDKwGM2RHDVrmawnb9or3oOfnTjNNj45TdMqgVHT0EO2/87gTBaeLE+rcSS/7dxQ==,iv:Q/KYTlEmyoytZcoIVICFrtTQ6qrvqIHD99KVo/wUxtI=,tag:mAO933ObFOImYWpQuAmN/Q==,type:str]
    OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4hzaVWyPHPgnVssPxgeTpnagRTLPJEAk4lbepZv/mNNvXQNqECGY0/hg8Ru5fLrwD4cJVsmjD8mnXGzrl7GNZw==,iv:nEnjftsPLrqXcpLxMJEzgGK/F4a3hIiXzKVfhuzeBfE=,tag:vqY7c70bDKzWFaAIG1msVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT3FGdE9VUkVKNzk4NkJF
            MzBiOXVleWkrR0IzS0lYajBNNW1IU25oM2lJCkNNbThabCs3M3M4NENyU2tpT2xY
            U2tGcWJLMTZpYmdZYnZjaittOEhsVEEKLS0tIG9TOCtDWEtMQk1zV2ljMjNhT2Zi
            S2F3aGpNQlJoQ1FDSWhIVDYxQmxhWjgKfagevgyJW1UJhbsAP6ktEECZAU/OcyoS
            yvNncXx/+Q+atqvv7RMaMXmT+fM85ohWbSynOVhLXvnwyxCWr7UJ1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T08:44:44Z"
    mac: ENC[AES256_GCM,data:jHF0CVgg8PkMCVfKMMJrVvAarfvuaq9J4YWHv99TsvvHz2mt3nKuVBR73kYE/t3RI8MdyMwsgmMjM/jFZjh5v38aP0/cgRAw3K2o7VvQaFyROQVzOD23cPN5OUeNMzkBnXhm/xoW5yvKleFNxxcCebsoSD6iMtOiK3eaTYIxGKU=,iv:sCKMJH9xtXVsAAVLJ/TLVrKuXfgYroWZGjt7YAOjkd8=,tag:IN+xgJUBUM3y7wP+b+x7+g==,type:str]
    version: 3.13.2
