apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:E/zojrEbu0ziEwVeC59h6ajVDfBmBw6GUZz1OE6bJWeIot+3Hh87IQ==,iv:HNYEDU4KQSk8M8eeX0VTjQabkU5Y1aGQDUcgraaDGqA=,tag:Ql4eAgsBNOd4RAdvEZZg4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMFJxRTVJbXJ6NVNsQ2NF
            bWhCZWY4cTdqaUlaYjRqRVRYZ1F4R0JOUDB3CkhIdEhnZHc0ci9hTGFaenJ1a09X
            NElzSW0xaUR0M21TUVU5bUpoLy8zM1kKLS0tIHl4d0ZRdzdoOUUvdE5hNzBZODBs
            MjAvSGNEcENBZy83T0FuQWk0ZzkzVk0KTPhfrB5Nt54lbHPvZA6u6fsDb/yJej0k
            Q428sN1LPOCCESOhLpsRaU6HJrQoZbIFYKSvqqEq9r5R6uY/fv5cFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:16:56Z"
    mac: ENC[AES256_GCM,data:Y2rj+2fcUULuX0crTKccGzmmDN8pBMdGBcLhxtgoIvfr+isk9NTUJWsdI5Iq6UlRy5PyB7pgjfY21HV2I9NWhnkOkpp2lYtvjd+U42hLPt1lWR/LokJYb7mybFQcr1bl15upk3verdmANhoO8frYCyqPx/HUk5J+N1Hzg3uQ3pQ=,iv:HgJxt757wDDFBfBVrcwv4y5Mni0p6EPStEhCHYPKEpk=,tag:PQeNCv/ySFnbSCsVSrULwg==,type:str]
    version: 3.13.2
