apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:AKSn91YTm9wQweBH8yrz7se2qy27y+M2sXriYkX4IXY0mTYTONrQaQ==,iv:gGylFK2Fy+3fYSEj9cbXkKJrh8ehvH3LcxYhZPsnKh4=,tag:OKr1oNlWooF0YBKDBgNvkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTmlpRzBucXdzK0lCcE4w
            UExCanVncFZ3QS9vaWNZNXdPalRiNjlLZUNVCkNjNGtPNS85dHR3a0tEQllla3lX
            UW1IZE1acmsrbkM1T0J2SnQ3cngwMVUKLS0tIFQ1QVVTY1FNYUJHMkN1eU9NU1ZE
            amJzVnVQZGxaZXdHay84Um5pTkZKNjgKnjB4VXRBVwFxfbXrskmjValr8wfZj7/4
            qkutNJsgBIVqBdGq4bdeHOMfKsLS0PXSajtI+zPD4kQ9VAqyfm6FiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:16:56Z"
    mac: ENC[AES256_GCM,data:VElS0ktX/18seFz5Gexdr7pG6sUsNtJ4aNcHN9F0+Pb6VkMyeHa6r7/xWFARLrfiixnLwM0vNtF51I9Q7leym49UKTtOAnBFCbTrYSmWlsVdMgY44Oj3cwmua1CLS03GMM5oEDF5lFIIijfQP9t+7TMxodoJ0CMRYaNiOZuKvfE=,iv:s9XU24eLYcM1nWVbQeCXzQaiyDJdQBF6KKLmKJqYEtw=,tag:883DtvQo9Gsb5OzX80LRRA==,type:str]
    version: 3.13.2
