apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0pdxymRshAOABLscwD7aneIG5Mv8zAxzDlj0pDc/tnQj6Y2SBVrAJzie4Cskz9x22aE3XfHfL6zE7r00w+ntIyJtlY1NBfY47obWYIprDkiG0FHmx8NOHg8Gx143v2+57+CttshXzlpS0gsJG4ccYPbyX6UfdDpivM4PCWWLXcqPM2sD+PoVwjZi2VakK4LbBDB4RdKq71l+2gQZADjbFaGGCCD/QlTot6dHTrFg6mjhxj2Csv+5LA==,iv:yegimafaGp0Cv1Z/fQC+1CcV7NtdS7IzbODg1K3oxMw=,tag:YbcBc1RVGwjon1lyctn66A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb3pKcHArT21xM2h1MkRo
            eEZBb3dNdGs1U2R2cGRXNThwNk00b1BIR0dzCklOUVRCbmFKakdlNTh3K0EwWURh
            R0o1NVB3TTE1c25wbDY3Tko4SFFHTVkKLS0tIHQrVHdLeUlJMTEwTitYc3JsVVRz
            MnJhQStFZjVEbFFQdjJLN3JJL2phb1kKJaijUOzcLxcM3g4usqraSzDpoUPqEKAB
            3AXfRfM9EFd1trDTsDFhAc4SfcT01GIO10aMuTkIYs1CpWyezIhylQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:16:56Z"
    mac: ENC[AES256_GCM,data:tT/NiybOhj954CxqWwbVLq5eNTfwAfX2GZw8tVnhtWR7AWu5RDRDSYa4WavizPyBEv1iVpVKenu4iENOzfiHA4RaNX1YTcCxRE5X3GzlCRLc9+yNE8a3VweMtinVbJ3ammNELQJw/XRh4hswtvR5dGYeun2KJs5taT8kFB0td6c=,iv:KIZV9bcw9ABX01Jt2mCY2O4urZHvh9rORb9nrzZcUvk=,tag:Y0YigDeEE998E6vCahDGWw==,type:str]
    version: 3.13.2
