apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: argocd
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:wxZv0ufrZyOicXpYhRoC7mZ+sStCezL8bSwDeibTOWudMQh37rwOeEaUmw==,iv:xgrOVMFB/vG/0g3kononSoHHGTkK0HZKVr/iMj8JK+A=,tag:X6cL+aFA9Sf6x9eEheuBqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa1hPZC9hdmw4QkRzL0dv
            WUU3ZUZqb0VOc2Z6eHJRVkVzZWpWTVBWZHlBCnZ5UEhsQVlvVzJGZmkyUGc3SGpp
            ajFJZ1NieXVpNXlJUkNaaEpiejh2bWsKLS0tIHVWMENQcFpFWEVza3N0ZEY3Sm5G
            WkQxcmphbjZzZEcrRW5KcXNCV0x2RDQKlCTmdCnuLm0faKLzZcay6H2DmgfLx67i
            UiG+PaIrFv85Qh0p5Jf/lIQuhJC2/5kUbLOC4RqKdbTv+Ki85R7U/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:46:15Z"
    mac: ENC[AES256_GCM,data:lj4Q37Rvjtq9DOrctVpW3wS9WgBQ953bFxMz09acEjOtgBEORRrojBrDxFNUIykJcQl9U+hDekRzSPtAvhBQqJEUVDkSNyJGTwnCGV27puFwbiCfHHlay/unhKjL6vXrOF3XH2zRYQluuGwJX1j/qetCoQnhoSjeg6qxlWjhoJY=,iv:iV2J+vCpadXMy6vNWPQNrZvQTpbR6fjYkZzmsHPR1M0=,tag:IRB7Xa1f2urGWM05hEpgbw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:9Sy2bqLXjqjtCSc4WUvRiFeB5wXKtXzv8NydIByXTNfm4HeBBYX5wf7kdw==,iv:7Rgr60ITeYD8vDVntPKTdXXBj7YKRuYt/b9g0fBksFA=,tag:RTdQRRBcCK4/Y7G6OHHnGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa1hPZC9hdmw4QkRzL0dv
            WUU3ZUZqb0VOc2Z6eHJRVkVzZWpWTVBWZHlBCnZ5UEhsQVlvVzJGZmkyUGc3SGpp
            ajFJZ1NieXVpNXlJUkNaaEpiejh2bWsKLS0tIHVWMENQcFpFWEVza3N0ZEY3Sm5G
            WkQxcmphbjZzZEcrRW5KcXNCV0x2RDQKlCTmdCnuLm0faKLzZcay6H2DmgfLx67i
            UiG+PaIrFv85Qh0p5Jf/lIQuhJC2/5kUbLOC4RqKdbTv+Ki85R7U/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:46:15Z"
    mac: ENC[AES256_GCM,data:lj4Q37Rvjtq9DOrctVpW3wS9WgBQ953bFxMz09acEjOtgBEORRrojBrDxFNUIykJcQl9U+hDekRzSPtAvhBQqJEUVDkSNyJGTwnCGV27puFwbiCfHHlay/unhKjL6vXrOF3XH2zRYQluuGwJX1j/qetCoQnhoSjeg6qxlWjhoJY=,iv:iV2J+vCpadXMy6vNWPQNrZvQTpbR6fjYkZzmsHPR1M0=,tag:IRB7Xa1f2urGWM05hEpgbw==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: hermes
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:GB3ID/hyCYvjHyarnvVkhq8ceWXC3KwjhYTe2gLLZAC1gQQt0r+11e3E0A==,iv:TJ0XuwcDzT7y55kfCsLJ+y0zChn6laPgWk6EvpUaEQM=,tag:HiEiX9wnaXjyR+VZZ4duxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa1hPZC9hdmw4QkRzL0dv
            WUU3ZUZqb0VOc2Z6eHJRVkVzZWpWTVBWZHlBCnZ5UEhsQVlvVzJGZmkyUGc3SGpp
            ajFJZ1NieXVpNXlJUkNaaEpiejh2bWsKLS0tIHVWMENQcFpFWEVza3N0ZEY3Sm5G
            WkQxcmphbjZzZEcrRW5KcXNCV0x2RDQKlCTmdCnuLm0faKLzZcay6H2DmgfLx67i
            UiG+PaIrFv85Qh0p5Jf/lIQuhJC2/5kUbLOC4RqKdbTv+Ki85R7U/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:46:15Z"
    mac: ENC[AES256_GCM,data:lj4Q37Rvjtq9DOrctVpW3wS9WgBQ953bFxMz09acEjOtgBEORRrojBrDxFNUIykJcQl9U+hDekRzSPtAvhBQqJEUVDkSNyJGTwnCGV27puFwbiCfHHlay/unhKjL6vXrOF3XH2zRYQluuGwJX1j/qetCoQnhoSjeg6qxlWjhoJY=,iv:iV2J+vCpadXMy6vNWPQNrZvQTpbR6fjYkZzmsHPR1M0=,tag:IRB7Xa1f2urGWM05hEpgbw==,type:str]
    version: 3.13.2
