apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: argocd
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:j3HFGkrrx9qswCrrvsxQxHdWsVMVyK803hIjs6vcuc6Zsw3EK/JT7eU9MA==,iv:35cSU9/wrkrtcA/AxJWkWcDPRlUOp+qXqefglZnr4ws=,tag:BOvxSWqcNsGX6QOvJ1fGow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTUFVeTRPUCtVNTNzWnZn
            NDVYOGxKYk4rYlZQaDR1Z0txeUtpeFRjTjBvCkVheHdKMllLNi95U1VONUN2MGdC
            WS95TVFDcnJTTy9Zb0JpcW5FYUZleXMKLS0tIEN0OEkvOHVBb3JRZnF6UzgwOUxY
            WmhKdjNDaDNmTjNEQ0gxUjM4V2hhS00KGxJUWF/e9E01sR8YjH9/jVXx+6Lq5vgP
            81hbRRw5gTb8RspRpTuCymT1EaiuGT4qD44eogTDMQFuS7KW80/30A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:36:44Z"
    mac: ENC[AES256_GCM,data:0XLiRtKwDxRRQUj9M3ZOS172bFPQviHgaqNfgcPhukk8iRs94zOFPGavlEFUAv3crjcrdsZkZLiLcAzjwNhN6nXdPzjtdB3jPZPY/e5SEv/9AdObj1cpLgFEW/+bmasEWiugk1XOWkjasWIrWRjWj2nKXPcli087jdsJHVajN5c=,iv:mWdJ3eDG+1orrxbsdhp2Q8MsgCdWB7+VlVB99eNxt3I=,tag:OdjnFKKTZBCvC9OVCSU+sQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:TVivgKe41yACxvKY6E/jYK2P2G6k7EngVVyeWte0af2k9Vg0lIDBc/FzYA==,iv:9baBVFpPFm4L5MLzt9Hhl/JkUW31FUgSpGLe7Oh9a1s=,tag:CLYu89bLCdy3EfdMFPaYHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTUFVeTRPUCtVNTNzWnZn
            NDVYOGxKYk4rYlZQaDR1Z0txeUtpeFRjTjBvCkVheHdKMllLNi95U1VONUN2MGdC
            WS95TVFDcnJTTy9Zb0JpcW5FYUZleXMKLS0tIEN0OEkvOHVBb3JRZnF6UzgwOUxY
            WmhKdjNDaDNmTjNEQ0gxUjM4V2hhS00KGxJUWF/e9E01sR8YjH9/jVXx+6Lq5vgP
            81hbRRw5gTb8RspRpTuCymT1EaiuGT4qD44eogTDMQFuS7KW80/30A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:36:44Z"
    mac: ENC[AES256_GCM,data:0XLiRtKwDxRRQUj9M3ZOS172bFPQviHgaqNfgcPhukk8iRs94zOFPGavlEFUAv3crjcrdsZkZLiLcAzjwNhN6nXdPzjtdB3jPZPY/e5SEv/9AdObj1cpLgFEW/+bmasEWiugk1XOWkjasWIrWRjWj2nKXPcli087jdsJHVajN5c=,iv:mWdJ3eDG+1orrxbsdhp2Q8MsgCdWB7+VlVB99eNxt3I=,tag:OdjnFKKTZBCvC9OVCSU+sQ==,type:str]
    version: 3.13.2
