apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: argocd
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:kZwKuA0t6VtqJW3dHPsiMDx3nyyQRR6ewpsbdUYe6Fu2NjLnsiHJv0LQgA==,iv:yqk/zAfLTXN9LV8OVy4B2tvY07DlNYGEQ6qtQK02oOI=,tag:FKwIsJ3nCRRK3UF1sBSOrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZmpnYmVxQ1hhcGRsY21O
            MEd3QjlQQ0JXekxSQnVmZWpxdzVScm54U0dZCldIN1NNZ0pmUXUwK2tkSHlKaDRG
            ajNZSnlUdFJiZGFjOFpZYUVoak1ZTjAKLS0tIFdCYUlCSjdRdG1XTkRka1RjdEVG
            ZTZFcUpxN3VmTHBjZGJUVDg4bFZxRjgKv3d1dESDrnps6GcgEdb+CAp0PSN2fIw5
            6D+kv0i5nJBePOpgboLHMkuiULgMDE0Gnr8YK0nJjdSVRuRD6bVBPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:16:56Z"
    mac: ENC[AES256_GCM,data:erDfMyqUtzKH2GXz3kyy6K9aN6IuQTf5w9w7TtVmRTItf9nLZYQj1OGRMDYUAOnISboC9wRj3Yr7dBhn7JLXpiPDkQeLpCTmvsj/mkHpyC5GdTArP9ikqe5icL2a5OsvJHq6FYqw12VhwT68ClrRFJxULDLonU6qqc8ehYNaEco=,iv:nXfWyunxo2TDGpEv4XTBpbLuDFGCzGyA6ecoxW2nqVk=,tag:qcQDoXvlIoxy5H9U2ATOCA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:yUB/zSJw4L1FsWdUMqfsgI6iGmPnygVuuwxuLOKLUGTM8oFkSMtFkRemhg==,iv:JPF+HuaxUOx2XM6Gss6hJla9YY/9DD2S3oC6fBr41Ig=,tag:xJCyLlzIbBINc+MfqnpjWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZmpnYmVxQ1hhcGRsY21O
            MEd3QjlQQ0JXekxSQnVmZWpxdzVScm54U0dZCldIN1NNZ0pmUXUwK2tkSHlKaDRG
            ajNZSnlUdFJiZGFjOFpZYUVoak1ZTjAKLS0tIFdCYUlCSjdRdG1XTkRka1RjdEVG
            ZTZFcUpxN3VmTHBjZGJUVDg4bFZxRjgKv3d1dESDrnps6GcgEdb+CAp0PSN2fIw5
            6D+kv0i5nJBePOpgboLHMkuiULgMDE0Gnr8YK0nJjdSVRuRD6bVBPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T09:16:56Z"
    mac: ENC[AES256_GCM,data:erDfMyqUtzKH2GXz3kyy6K9aN6IuQTf5w9w7TtVmRTItf9nLZYQj1OGRMDYUAOnISboC9wRj3Yr7dBhn7JLXpiPDkQeLpCTmvsj/mkHpyC5GdTArP9ikqe5icL2a5OsvJHq6FYqw12VhwT68ClrRFJxULDLonU6qqc8ehYNaEco=,iv:nXfWyunxo2TDGpEv4XTBpbLuDFGCzGyA6ecoxW2nqVk=,tag:qcQDoXvlIoxy5H9U2ATOCA==,type:str]
    version: 3.13.2
