apiVersion: v1
kind: Secret
metadata:
    name: ghcr-vasary
    namespace: coins-inventory
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:HQZoRW2Pfp4VCxiO4IOCBd9YyMg1a3DQdd4lSkwD7rT/ejejsoEeHGBa8QTVgFcRP13McP1FxgybF3qdsNt+JYPargH68YbXM7IhlWMG6XGCOfxdLO/ujvTCLlRrkzetp++EgSCoyUTkhT/H3xntsaa84BZw6+PtcPRuRBbuXXZ6+YOdSi4MIkt+wxd0r7sxQCHkZniTEjwbW3pXPTTZPFk+0t71GZ05m2+w,iv:/CjcnsGAe0p3uGbJKPZVgSE8iDGWyRhFUHZi1ul6Iq0=,tag:AlWA5dDj3IfRaMAq4ZCmjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbXRPc24yUCtIL01QeTM5
            UDNXNDJVNHYzcXRxOWludHJjMlk1MzdrYUVFClBrRWJKbmhVcnhEdWc2NzhzalJ5
            UkZieGNOVXRWTzdTZXZWczU0RGUrYUkKLS0tIDN5Nk5MNjZZcThWdXFVUkJnZmdu
            RkdRZFVZRHlWQmFzY29BQzZJTzc0bFkKboyh4wtx/QHMcg1Ohem6PKkRCy1beEe+
            7ZHiJGMIIMzaT/hj8AahZ3t2PQcDuxVpfPFHdFeaGWsTW6ZsSnCnvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T18:39:18Z"
    mac: ENC[AES256_GCM,data:kG+vVUzbSLgzHfEkH7YHvoeAuXBmrRNLZhu5ymv/AQiI/EvHJpU8E9G5wdiiNAuiOLtpTMIOXqVZYE1ddxnDjD4hU3ADBunTfX6gva2lC2gmpjhDnP2/Z+eni8ItjkytlDBiuhII0bT8g6lfkhKRj6dCSPQJY+jzS8oGNiXAbfI=,iv:lv3wvPCk5mKtUJIJDhHKlAAI+3rnQYnAWn7dFp4ELrI=,tag:xGYKLgakpPIhJA9BJcf9Ng==,type:str]
    version: 3.13.2
