apiVersion: v1
kind: Secret
metadata:
    name: coins-inventory-config
    namespace: coins-inventory
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:Y5NVW/fLdaZ5AmaAmwqQjQRwzyWY28KidOwgI/1ugS5wCJ9sf5GW9OmoXn4=,iv:L7KYO88/FaDt0/RJ0eJ/la1n0L0PWfq7e9pJ9QvWz1c=,tag:GahusXlZ8ezObbr25WP2Vw==,type:str]
    .env.prod: ENC[AES256_GCM,data:NJjDOVGnrbiN3jCEx70hruaB5XjfoVCJmU/H0exKw4BOODMr20Vfp3I9SlALoulQMFPK0SA6xLpTQ7loHWiapUwPheKg1odqaGM1HV2fHykLNfMetF9UlR44HqbcK7ToQ28MPZ6PcoCPzrmhTGC1n1RMwUBx73k5plLAHUmg2rCFqShlxofSdffOFTWxiL5tNQ5mTVVQlTAX1nLhU9Fna5Orq2ay1fXSdsoWPPX3zJxeM6cFZoeD3R722H6RaACE2tc45N+YTfL43cpKDKNeRoakAZSEg3FU4rXo289hK0KFUzD/WS570dqAHROvw0Bd643V8FJQ/B2VKWWuKZ+Gtti7wAzxN6Kq,iv:ewRqtxLPGylz6i6zY7JAoUntPx+JQRorjVTmbjw0zaY=,tag:T2ZYVdDS2SkZ2YeOlb0pfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMnZyUzNWQWhPRzc2TnVH
            TWxLL3h5ZlBkWmlXZ2lVVnhZRXlYWDJLU2ljCi9OazV5UDRPb3MzYVVTeGNZMnJv
            NnZsSW5WWHVKNzh6Y0E4eUx2b05uOTQKLS0tIG9sSk9nS1RTOFdBT0J1Vk1KUUE5
            clVMNWJqRGtTaXpsRStWNHdtS29Pdm8KtkPQAoSzxd+Q7Qkw/ZOlnAC+axL9sD5t
            m5peHYNN2B9dlcBfkhs+keLlZfMmNHlc2QCXJzvFKkM98DdjiVgYug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T18:19:39Z"
    mac: ENC[AES256_GCM,data:xPpqtaBKdoX6iKcTp9vKzc6cEybXuabV3PMgEmuZCSDSVADTVbfzvhGsZGS/VHcLf3x3g9xsngFey+5hcPRZMFAnt8UKz78hQKLgR2K0+6wa880V71sMAzE6spGErBAQ4oyRBElgqCdWg7uvAFPpg89v1KqOSDv4sm0mIJObAlY=,iv:MRg7EEYvXpgeBgjSTom++OMpnTXvc7Qh1eyevhREtoY=,tag:91dxJ72yxLUzLO8NeLYx8g==,type:str]
    version: 3.13.2
