apiVersion: v1
kind: Secret
metadata:
    name: docmost-secrets
    namespace: docmost
type: kubernetes.io/basic-auth
stringData:
    APP_SECRET: ENC[AES256_GCM,data:kbI2rWis87j7yZRq/YhXdho4191yhDfwdFMsPjvKx0OeFbNtUzYAWJiTg5SQJqjJ2Y2P/0vOfbYSmRdGZYj1YA==,iv:SzmuKLBWC1AbOUi60vtdUQ6asntIp3Vs9WiRgbgJZzA=,tag:RgNu3Q0aU6iNeV81JLJCpw==,type:str]
    username: ENC[AES256_GCM,data:cbh82eECXQ==,iv:CF7ZzlQLvLQESxAL0OCe/xN5K3qGeqRCE+lUcE/ZSOg=,tag:j2i3Vsg6XTuac2Hn/3v1UA==,type:str]
    password: ENC[AES256_GCM,data:PDEOOWnLxO7C8Xl1X4lr1nbwXusHXLnuLGegbFg79G1gOyeCvyn8N4R6WDhFECEI,iv:KvmUd/wpiLpGiHCWlgvhsUVyxbswv0c8su+w2wc5EDA=,tag:42vJrKWeXfEc+Hhqu3ep0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPazErcFVaVHhKeFVrdC9n
            TVJzWkFZRENlQS9NNnhrRXV2RGxCUmRKc1VZCk5LY1Q1K1N0ZzdoOXBBT3o4N0pE
            UWJVNE5DUmR1RWJVK2FKUE15Z3VNM3cKLS0tIG9pWWZOTTNIOVhFSTBoWE5EdGow
            NFBlZUxEdWYzcmNiS24vOENiQURiUGMKr7BNmm935p59alIhbcK7XsoUTWr9Js3B
            rvWhahVnZyqkd+6Opj2gnwIGgjyvXLXyqihaRUkP373w9gwnG4yFFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T15:57:43Z"
    mac: ENC[AES256_GCM,data:4geucYNr/o8o77HCAM9arlpJnPSIrfN+zA/cSMsRvp1Cnb/1HHSaOdG+7PAQ8K2dzxz/+bTD9jrLVg899XmX0Xxy+SQnEFb5/8fQvresl8kij0hk4e56lRkAxUtE8Wos3qgK/mjfi2FQHu0IRvGqKBXieDIedx5ZiueF+6dscI0=,iv:h2TDOnY0Mby7kDmh9YuRvXvdZo766u26buQlj6dZh6w=,tag:LmLY34JmArXBWjjQeeZK6g==,type:str]
    version: 3.13.2
