apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secrets
    namespace: freshrss
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:IeuxZQwF36IcjJ3tjHJyJqemoF+5H6iu4wr4B/oHdY1t9r6Wmxxkp3jqPk/xSVSdfSE0WMQCtYN6c8Egql+7FQ==,iv:tYUYBqgc/Dm2Ixqh5Lnq/5jhKVWORA07Bed2CmiyZ1Q=,tag:razMtEQSvKlK4vSt2N0lfg==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:BvrhG9AC0cA826Yj3Sta4WXyy+sqEx4lNCPHRoZLcTuTY+kv3xQabmacdQ+Px8s7lW87c4+EmTnEg/6X2mBfqQ==,iv:Ypxfmi7Axj8mFAhRPMSr/mW8LdwDSajeA1GB56PtJ9U=,tag:dE+SK27LlyvljrZJGy+xQw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wst6SS7n3tUk6o5Q2Vh0xCWn2UeXmzREKDizw/WwNTvR84t/Xt0kIpjkFev5zE+GHdqYbN/lOF6MrFt4vCGtvA==,iv:fVU0Ud8fQgcW45Jyqp2uaIIhphV4rttBJYusVLmQWRs=,tag:b9+ewIK7TsEaEu1oI4CicA==,type:str]
    ADMIN_API_PASSWORD: ENC[AES256_GCM,data:mH5GPWxjgjLI3GSfpnoUGPwSiQpcgE4twaUk3hGk6RGyNimxCijnfXyXd9XQScqOwEFiRNG3d3NDPjFqN/VbPA==,iv:CYiVhNBgu1XFUWhSJxl8xvRHFy1w4ADY0uLEwfbMRUM=,tag:D6N1d82k+yKykXNOTAGFEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UjVNRHlYNFJTOUN0eWhD
            Vk9mdTJ0amo1cU96Ym5jMTRoc0JZcXp2cjFBCjg2ZTlnN0ZtSUNuT3pPL0R5NWhN
            YW1IcS9LR0xramtob2ZpTDcyOC9hV0UKLS0tIEw2YUg0TnBnTm5SRkdyZjZsYU9F
            dGhsTVNRNS83bWpOS2FFeDVVaDg3QTgK8ffExGiGqxX12pACCcmLCSwZJcB1OKhr
            D1ELGkBKuuEWtCKxOsGAGIolrZ3s13mUu618aGTVPriYl25JqBZ/3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T20:46:17Z"
    mac: ENC[AES256_GCM,data:u9fZ0D1WM+xAiVIonbRHcWMAva1W+AoD+Xy730ATYx8tHNCU08HhpTTPPYD1ix75ZI1JhzuU4tDrxT45vDyCv8SYtLMKGZvkci0tIy+MPzbYQrLYbHroZWcYoKxtGvFizeRK9oOQBPoFHZ5N4hqrxraAS7M1mDTQmXvP/kyWdZQ=,iv:V/LJIUJiUPjUW0MX+vZI7ccl7M19AAeeCJISy1nJZnU=,tag:bpa005ZsF2j/VriRRLSR9w==,type:str]
    version: 3.13.3
