apiVersion: v1
kind: Secret
metadata:
    name: github-runner-auth
    namespace: arc-runners
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:BsHywQkQa8q65GcDjAnb69tVBj4Amf3W1d25V/0=,iv:hmqNN2jNB8tkmo2aEUfwe+U02K0Hj5pxn9oEezRSbRc=,tag:JOQOlhtNSyoF83tQmgPwNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM2ZnMDZZc0tLKzNYV05t
            S3NaWSsvVUlaNEQrL2FCTklld2J3anAzNndVCmhkUzRDcVhXRnE4dnU3YjVvOFIx
            S3pOd3BtQndmZEo4WE1ueERLOGxaTnMKLS0tIEhxYnJTTmNLUjJGZXk4WUR0TFpR
            MTIyTWlFeTRwZzJiMDJ5YTBLYXVUNVEKctfMitaDutOTjXtDun2aY7iGYGvXdmLy
            CzQ2YH2+YVpkQmTyo6Zj8d7uyNypyvH5lswU3HpYd42lTQLAtT7kGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:05:10Z"
    mac: ENC[AES256_GCM,data:M9BC28QgpZ/LsjwvFOdz88haciw1qFWUiE5lD3CPf33MBNJJP8mmleV4Wlvc72OX/zIedhVlJ7eYOWmXvIgjGcYpEYGmmwyAQHoFmGpjl9sGpTD5kvV1uCNuNZ+FykdIJLKwE4E3TJUGvCtbr8FcZqeRy02k30Qyg2fvXn3YFNc=,iv:4qRRy1aaAiTPQCcRMMJ/za6E/cdy9Yq7c2aVUTERcCs=,tag:VEodk7k/Zw9kzwf3ieeCiQ==,type:str]
    version: 3.13.2
