apiVersion: v1
kind: Secret
metadata:
    name: github-runner-auth
    namespace: arc-runners
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:21/K4LAZZMaXWkqpd29ZeLREMoGv7CU0EIiwM5IqKxHOieXMqtGv/A==,iv:+Y0RsMCFl7o4d6TmPsL5UTQTJP6XRuvUVUd4R5l254Q=,tag:PLNeHyHSxx5riRUqq7MDSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcVVHcmNKbUNFZTI5SHdG
            UXdabHZZbUVDZjhJQ3FkbWZtejBkMEJWa1FRCmFQT3BFZjRrSFpESVRWdVVDcGp4
            dmlTV2lHdmVpQUZ1ZkUzaGRFWGlrRkkKLS0tIEN1TDBBUnNlMDUyNm5ncDdpcFR3
            ZkdFNUZCaGovZktLTUJZaGU0RkhpZ2MKxIxvw7quSXvLKP9Lei4/dGtxsqw+XIq+
            EC9+uLi0yVfR3P8u/Db9dhECFxh9qwgnv39sUH8++TCLIz3ZVsantw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T20:18:16Z"
    mac: ENC[AES256_GCM,data:TPdi9bPD26SP9PgjiJjge8fkjn0Dvy+DotYNdsjZEWOs3BYyhkvqEcgemF6l0+UK36psqXX/Xxq+JbHcZRZ6dxsEzfEci7Ip37azl5TMHPVkt/YONQLqHp/FfLu2eTFGDBMrrcUJeiYQbraj5NHDboTRq2H6UoEJ5XcjNKrSW38=,iv:4D02zmS8lhMI8zKAPWK0YLJHcLxuJVV5+sLafrnWric=,tag:TgV6w+20HwhVPFaozbvaBw==,type:str]
    version: 3.13.2
