apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:P04w3Lv07neXMnRO6z1IkXxPZeTHYN/+blY5uaOpUYw5EUXyC8YBcbxNjaGeWyP/vyRHwSzoSUXVjlOCUJ//Xg==,iv:hcsXd4wI1l7PNVw5A1Z0CyhjuqWytcU8SPUtqOQ72is=,tag:L7X8hfMps+n/+SM369o3zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZDdncU9mR2Q2bjZqRzZq
            SWcwSXloOVBUK2FwcUI1T0t4UmtwRkkrMFM0CjdadlkxaDc0TEFCN3htMGU4UmZw
            OEwzUmFUL1p3OWI5ZkFKRTErYUkzRmMKLS0tIFM4M3lGRFRSenJDdFFiTEtnM2VR
            dFlpa21ldjR3Q052d0RXWHQ1Wmhqbk0KtAy0Kmb5CBJ917KjAxnbksWQ9rmkKwJA
            B0DV53MckK4UJJupJ6EzHdQdJco+E9j5Rj2xFNH0shUGMPBp/9Mqmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T09:24:36Z"
    mac: ENC[AES256_GCM,data:cz+8BgzB3FnJXqSvrq3zTFmmEPTDGAoxy0ZkSh3Q4W+hziLZN3hIYaHyG5g/qMcF3jFtWWDmRdQHfL9d40hoPvL4Rxm6VMelxAL3qsohDlVl1iKBvAD9jJxD0mvX7qjzq5vTPEuGwrmLzc+geFuneczGiSJYFrf6nLsxsRUBHh8=,iv:0yVMagDInWnitK5he5/pGl1pch4u0AuF4fmQhe6lvdg=,tag:YKfgwBlgUCCTZMWZNup/kQ==,type:str]
    version: 3.13.2
