apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:QoYFGDdo+o1nICGpM2G1h270FSVaIUTxouHO3myZoc7e7yt1x0vA2E0rtExrtw==,iv:VemxUlhvMdG9zhrss3EI1eKW/IIObTbOnPAinSxwNvk=,tag:sauJULFV6PUEuk+vi8Xa3A==,type:str]
    TELEGRAM_ALLOWED_USERS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUG9ERVBKbVdYNVdGOGRZ
            SGxvY2ZpNHFmKzE5dWpBVlJBbzBJTnFJWUE0ClVrOUpnMllqSXRreHhUS0pPQ2po
            SlRyZ1pwbjdxMGJJMnF6cGJSMlBXM1EKLS0tIFZ4eXpnOFhJYjE4cXlWWm9rQkll
            NHNDVmFxNHpWcDFrTVVPRTM4VnkvaXMKNwgqvLvA4BR2WIHuv8KbK+t+gY1QKIT/
            n50LA9Fm9rvYZNV+R9NSF8Ef6K744hhzzUvgI7EJHVMINnsHTBIh+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T18:52:51Z"
    mac: ENC[AES256_GCM,data:2O7CwPpquLKru8sj2gY5cCaZxG72pZG1DvA+a9JWizqQXp9rlzseGR1zLtKGrBl8tP67oY93Kfc3NVGaeyCSvkhjQXNu3V8ASOPvMbHPKpssVkMs+4cDGOEde/54XYlnKFuBYHUZsIzakOZNgUDE9cPf6n/8uW7hwifKZ41NZfg=,iv:vk5lcYhnxJQZ4HwPWdu2Dm4OK2ujwMXhKm2oEEOWfJc=,tag:RgrD0moelPJVChcpifCggw==,type:str]
    version: 3.13.2
