apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:jrKfp4SWcqEXmix1Apx3tS5zL+UP7QTjqw+F9eBveTKegmTpFJK8RuaQf5RA2g==,iv:mKVJ4+kM5aNulRbQQ8d6fLqgewkB2c9OFjv15i9svYI=,tag:ANyPnlTmlFq95XReZbCoxw==,type:str]
    TELEGRAM_ALLOWED_USERS: ""
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:132DBP4=,iv:Xnl2Lm9tqy5EHZVP1WgCD5hhSfljLBMnH0BBHoLOB1w=,tag:gNChlZGGUOTR6xVs26g7nA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:4l+Bwu1lr56xPN2ImDXP2Hqtfj7JpZIH0IepyDYuTwo=,iv:gm3Fq5feTDN414fb7eYHoMhAPNI2lFskAbk5mQVhCBs=,tag:FRSkUHNm4hI9EcE8qjx39w==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:GDaKY5+6sUW5d3hEReyDw0RAsjr7l7clcRIQKKSrt2tRc8HndI/FB3OnpQ3gTy1d0An2xe+Qo9vn/ybBgCa85A==,iv:sNSwCQ1voMKXnT7PFvvJgP7pgW6BTMzK92EODy1GyPI=,tag:yIofjuq/Z9xT/jOhd+56RQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbnh0L3p0TnR1eWI4R1RE
            ZExwMTV2YXZRNWRrd1ZvVWJLTGRnblczVkF3CkpmUVBsSlNQLytLTFhKNlBMV2dw
            Zkl3YWwwMFIyaWFrQUdWeElpbnRKVW8KLS0tIEQwbERVVlhZQkV2SmU0RUFtUDA2
            SU5DN2ZaVWhiQmJ0S1daNS9WK0VzTlkKUtqjDw9+0IiYPe72PDb+5qcAzir/gdkx
            zD2iW7H4Xs2uW5im/XbNLf0vicDlLIkyrjIjg2xlS2rBt2ZDqZlA8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T19:11:49Z"
    mac: ENC[AES256_GCM,data:1+SVT/k1Hk+kDBvOsLlmIVh2sPq0qPrjUyrHD0U5U/pTSvr1Gn3jOcWghd0yM+jslFi6C6uXl5O29ATKfmkE2xwm58ZsYBlNbQhNWxWOKItq9vf6PFdI3QbRnQ16QT4KPA4f9d9TWXBd48/1JGb6EKODutL+oCOFOwWQDJ3/5Mo=,iv:k1TDMEIX1y1a0O8qIukPEsbt0rcEuqhDnZwl0fs0CXM=,tag:TxsrZ+8/4ADLAGS07k7smw==,type:str]
    version: 3.13.2
