apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:KB3QInnHNknTTB88nec9BMdsWJYxK576uJIzXlWd0Mf23IwkDacJNfwWJhdo7r1aaJsVN5TH0DDt3yvFjjCfwg==,iv:KqUTSYGoqaYo6FDtDdnKPQD4DF/Ddz6xI7kzEyR2UaY=,tag:keQ3hj0347Cpny7CYy8X2A==,type:str]
    HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:BfERX7yic07nnWGoMIjz7t3ofWAa2r9/uHHaTSiAm72dEGm2eUaPNpa8XUAAxASSrjZ5shDh7cW4Jo9rtxx5yQ==,iv:SuNnk0L9cXtdZg3cP1i9gE8UMNVHBHp2jA/F/AuIsk0=,tag:jOmJlF8tsm0Wea1I6X53HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ2RVZCtFcTdwaUpxOHpN
            L3o4eWhYbmExZlhsUjNxdGZUVTJPYldVREE0CngwSDNYZ0tTS0VUYm5KVkgzdk9J
            cDBlN2RYTWMrVFp1aVZLUDg3OXdYLzAKLS0tIDNIMTNmcEJ4eXF6b2RBanBBdm0v
            cXNDN1ZFaUh5ZHY5OHZKa0FCeFhaNXMK6fbyuJA6/S7JKJWaijcUKt6q2UO4JH5/
            AGHY9nqwDaIsqsbt+d9vzoF3FqXEpydWjtDNuXWu51JNvFXO3g+u4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T10:24:43Z"
    mac: ENC[AES256_GCM,data:vlz5zOXOAzYmpmgj0S9sHopmqC0hpZSoKJQPNUkDOt0t+iCf3yCbZgT1RxbgqpHq9O07Ej51SHKEN7YVBGWBkuynAchiH4mTKQ6US/a9qjnWzEHyrikV9klRD8QYYXiOpbPCS3T/ppQwnzDZQpWz+JzeUa19eQFet7YDuwWbX9c=,iv:LCuNBMMfUsiUgWzJ5Vz/zyeq1xRK4vXNpgN6m4a8XC8=,tag:JyKgP0PZISrScUS3JLfqQg==,type:str]
    version: 3.13.3
