apiVersion: v1
kind: Secret
metadata:
    name: immich-config
    namespace: immich
type: Opaque
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:VIjbfpDp+OGAom37K8+9RuJQYI7tB3S86YZ0JwrP4GN05FhiLb8jY3K5vRrxtKjLSY74BDP3p0QvHDz5Wg9ygeLQdE9UKgHRg5Eb9vl3IEGV51KyUJQMquGcn6IdYCkMTjNjxn9H83F3NNMBdcaiMIpwfw//otZXPvBaoSs6lnf8X/iTdzcYbJzirtWGNq7lIR+jPU5nrNblfy1WPe1scq2wErUHt5HThGF0+SAjfp3nncy+0l045+MzR6TBm2mIVXDYIp4O+qhdFGm87g13iEMVN3WMXeNbTv8FhlSNu9K84jETgCT0zg2ir1J8VtY0rRozGJq5zW2sXeB6k/8fdVss+Vbg0HbuHHVjihZ3EjHgCU+TzL3kf8hWhODlthYbtOt1BlhWKPRXtHTBSw9RL5agqx7jI8fQB6UOtuwWtSRokhttZoYydLigwOz0yZoUYRMPDQ6yLsdSn3LkzYqI8xSp+zHll6L+zU0R9H5G9vQU3YRyvwP4j2pRSx3t0PUPEb5jJO3Pv1hPlP3mHy73F9oTZHqNMRpZNezeN5eQRG66cqE6l7AsX9IQoK1JbrBbuQkPidiTBDU8wju48AOM7M2btI+Oo9Hcj1M5gWm88HfLrbi9rUpA5NSP30PjiVqSI1aHBoBOzipPDDTRIfIOLX/JMHhexkb9JIn1GbnS374B0qdfGFpbXv5FZZ0ekQWIa/OQv2h0fQ27RvIkbv2XTXGTZeLHL2nW6Y7fe953izL3wRqAwXqAamZYy7ecpSPhekKwH/kbg4ThTKYPLGvZA1VvN3aaNJaO7K2s,iv:/Uj7dBxMFcCkRnOhhRvpblulbpNXdMM9OMdVm+AvTDQ=,tag:0axjf9wkKz26KC2LRzoerw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTWVGU2ZjNUpTRzBvd1cv
            b0dDdlNqUkdwODM4ancvVlBDbG5LYTl2VEZNCnpEUWhLdWhKUzVEVlQyNVhGUHU2
            N2dMcjdsTGlOM01iQUdPNnQxRk9VSUEKLS0tIFFhSHFzRUNvVzRpdTNjeGlGc2Yw
            TWVLUGZac2hPVE5CbXdFVk95Z2ppc2sK2aJfYhLu+5FN32r/H9K7CHt2jaNFhvaN
            1NUVpzpPEAHz6sOup4y9wt7N2B4hJSH1UF4FQQGFW4EzGmkgSOe/Og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T18:48:03Z"
    mac: ENC[AES256_GCM,data:JQLztV8KwIuvwhfo+qLRvCE7UGYxdlFFeBbCZTYa+GtU7XPcupQwm4vREtQnM5wsGeZ33E1Y77zaKKxkYzROekaEBY61VlmlawWxFhZ7Oer5uxuIpsGMogIY8Q+ZIf38aZBg4aNocl7Uq+g0iCpgCfZXgDgjWF4AhCZgBAyDZeY=,iv:I2mWiL+so8PT8EaUZ7CkPfYCeyCRmcItHSteiaUiLZE=,tag:9Q4IZSvRa+5MRoNkEgyyww==,type:str]
    version: 3.13.2
