apiVersion: v1
kind: Secret
metadata:
    name: librechat-credentials-env
    namespace: librechat
type: Opaque
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:ewy/dLumRNGy2dODSltftc5bMkJi7VHtf7lSZ9io9s8X3mMpNuIvDTEg2HhIpce+ypnIIA7+ZpPsCFwbaDrh8A==,iv:UAM92d4cnGRIjd3Ao6oClai94E/iLqj+ae6PWq1tMVU=,tag:p0vb06ogapv4iBzpaAYNTQ==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:9ytHCDloJn9uwUDI2wt9QpOTR3t5NOuu5pgJSPbWEtE=,iv:xxNbgwR/lsodpL5dc9cf+qRDsLO+z/SPsLO0FJzwZUI=,tag:jvTGuokccFqLmsyjJRm2tA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:EiHyB2MR7sfK4m4A5Z4xMUlgz1ltmpf5fdoYQ/oNC22PbXOo1Jl+Vdomvf/LPQiHKH1XruNTa9T2BVy7h9OSTQ==,iv:IpLuGQ1G6zLrFQIS0rZcpDRPRJsEQ6jWmqyjnA9vRM0=,tag:KSeIAoQjKcXu9+ELTesfEg==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:0CwOg2g8w645hymiwde47oEJAHw/VV5s6oJgtdZXOaUAdIV+SZtvp8Bjnpi5pemaf9RifGHqVibpruCEl28dJA==,iv:iOWCkRgGuuYO9G9sk41TNDKGPHy1vVCZafK8G4FO7sY=,tag:0xqUa/FBfzossF4ok0BkoQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:OCtIHXnXglheO74QLRYWFDMJwxuonKTbCS4CrNte7uaL1CjD5uUF6aEDhqj3mUe+QmvTqh7lzRzJ68IwFO+EDA==,iv:mpj8H1gBkzUAILmQmszr1B7nPHsrW1NTnQNWSAMqXCw=,tag:IJJ/lsetRGzvAuZNuuYiKA==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:qYnuIC9SlfOxz6/CcI0vHx+ihyHXbWVUSYGScnxHgeUmsPzxl47hjXJGrLv8uUss2bPnVBTyjoFlXrMSNkKF8+Kwyhx/9XNrniu0XxkTsYcy2BZ+tSF9CTb4F+rgS+oQ,iv:rrvlY+GFKat0iZBj+Y5blsCwoFnmGubNbcWu61CfRas=,tag:y/4TeOBMEql64aSUwjcyZQ==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:7t+d5AA1x+USUND6o1/thdgC1rSsEyDjGo0BJ12VUlPHYWlLxaUVatU6j9iFpjFQ1e2UGX+rQGiyXFs89ARNvw==,iv:Rh8VNnJKLKorLl8KLxwXGQoE24Fn/ZLvLYjBrL7OqpQ=,tag:IIJH4fVLyaErCXV17JN75g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeDRuaGZTVTFCWnllN2x6
            eFJEWTBRdHRaVzBMMzBDNGZKK1JKVjVBVVI4CmxWQTg2dlM2NGFuL05HWVVLNFVz
            cENUaDk4TDc5bmYzRHZscVh1WVB6NzgKLS0tIGFJWjR0UC9PM2VxMjBSQS9KQmpG
            cnJMdjJ3OVNxNGlZT0d3ZXBMcDRkS2sKXTBAZ2An1TvZz3siaFBCfYrSSnnb5Scz
            od3vJHEX15y6EveCCjT0Z6O+ERWZm83HMAsPdB2+PDa8TDuJvF922w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T08:55:23Z"
    mac: ENC[AES256_GCM,data:Fx4sN9/Tepz2W+Z+/x8xt0e1fN/Nn4AQ4VJtDrC8ImD9ovYylqUDTs2UkAEQ2hy8zjLFIdCfP1vlFfPnMexrqgsyWtMoh1VJON6lUlDdX3gVrizxWDB6yuwwmp9X7nQC4/TE5ekxJMsSUOhjeu9wHYI3B7PBXaGZmQT/TK89j8A=,iv:flzcdlB8xeWJpQ2/3/Qk8JL+GMUiJJeHIebTjWxNDl8=,tag:/ReKRX1Cu3w6WzosclUeQQ==,type:str]
    version: 3.13.2
