apiVersion: v1
kind: Secret
metadata:
    name: llm-proxy-secrets
    namespace: llm-proxy
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:wz+DoXvk7AenMqzJJQh4L03c,iv:8RvStiG854F3kSfLATixEflpL1+HUcy18X+NeZOOAn8=,tag:aRYEv5toTggA9ijxmUjpFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMU80bkVqL2k1Z0o5QWdV
            TWVOSDd3UERGbm56eGxnanhYNkdmVUo5bHhJCjFSMTRvVGZOWElML0F0VEx2c0h2
            Y200b0FmajIxcERuSHdCcUlNbURrUlUKLS0tIDRnNEkvaHI5aGl4S3pKTVdFbEVV
            c2hlU1ZYMS9HZTNHb2ZjVkdNZlVTLzQKVZVpqyHjYTaX6/6adNqUD6tf5A1v9aO8
            Hucs0T3P7a0iTImmqPXtq4H3O5j2jMwYc7u1Vyn5aCArBKagZkx1mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T20:04:00Z"
    mac: ENC[AES256_GCM,data:9kVJTvr0AANynY/mXmG7CrHgkePaNECElGoehtTcfweh3peINvvgu5Uv5Vq9T8H8OFRFZnoLRrNdXlJ7GFMo3sF5qErU2MQIF3+e/rLVMkAwjt4yUgYJkA7EamYfZbWKlh2nv1IjoqoCYy8j1xqJeWxyd/t6AYH4jJsJiTreOBs=,iv:TmqKrt4aBf2DE+XHqWarStSV/SpOcg7vGDAwuR6NjBQ=,tag:8p8tPo64khX5XFBsesZkAA==,type:str]
    version: 3.13.3
