apiVersion: v1
kind: Secret
metadata:
    name: llm-proxy-secrets
    namespace: llm-proxy
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:xG3i7MPEUdUoiVACcX7rx7D2GsjxSzqV375nXRoBTcb8XIm4sp0mE7AOma7l3JRgvayU,iv:214AEX6YTkwAG1NB+1jNY++ixjHAH+YTyVf/D6Flb1E=,tag:iTsupYf0YiLrvKmfozrHQA==,type:str]
    GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:OOjXsTqnA3lOG+d97VB1NmHZIamimBmG3fnq81XcimYtq0HCgJIlGUI9y53TKzWau9Wlfnj3AR1fSO5DApCVJg==,iv:piJ+7Dvr+amtWBPeEKni25mCp4uY+pm/t7bsNIHOhHE=,tag:Ex2kkJhU0AFZYnIXPMHq0w==,type:str]
    GENERIC_CLIENT_ID: ENC[AES256_GCM,data:Ssuw0Y8Y3G4l,iv:gsOHlafQKJflYamzgY3U/vpyIwrWDp844XiulozzIQg=,tag:S+iAteqGzCMaQYqQWSjUUw==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:A6A6uMcG68zQeKArlA5hjQNxCisOPWA2GYs7ieo5RAAdz95E4TjxetZT4CD+aW4l,iv:Esv/uAdiClk1f376CAG1FDbR7TE+UsvoHCBKe2rsx5U=,tag:kpZdDsWJ6whm0FxeIfGUMg==,type:str]
    UI_USERNAME: ENC[AES256_GCM,data:mH2LfXo=,iv:PFinfCrieeG1HdgJUXr8V5VOgChhGfR9JflSKFCHclQ=,tag:pCbaYWJ5uFJ0XW2KWyXJsQ==,type:str]
    GENERIC_CLIENT_STATE: ENC[AES256_GCM,data:UIzBdusbkKJ43VT6ReVIHkYQS9DNWFVjvlvWYsPK9RQ=,iv:7JqwFp2uImIUKxFPkrMPtOtQWqUx3tYxxLAi0kpk/b8=,tag:wIlpYt7LxdX5d+wWK8/UHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMU80bkVqL2k1Z0o5QWdV
            TWVOSDd3UERGbm56eGxnanhYNkdmVUo5bHhJCjFSMTRvVGZOWElML0F0VEx2c0h2
            Y200b0FmajIxcERuSHdCcUlNbURrUlUKLS0tIDRnNEkvaHI5aGl4S3pKTVdFbEVV
            c2hlU1ZYMS9HZTNHb2ZjVkdNZlVTLzQKVZVpqyHjYTaX6/6adNqUD6tf5A1v9aO8
            Hucs0T3P7a0iTImmqPXtq4H3O5j2jMwYc7u1Vyn5aCArBKagZkx1mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T06:36:42Z"
    mac: ENC[AES256_GCM,data:abxqmwBhGlABA0e01yEnkIc4N6QZ+yi7DOaXvnZGKBageNqWly/TRCbH1t9TzWJvXXhwyvKonAZLx6e83RmMEdoJjkbjPvnLQKqaTxYgWLvMotmFc9WnBwwlsmsJlSz3dFLNyiwObZ2kD0p4R+pKhI5fo+XCuozgUoyU31PH2Bo=,iv:I7p6vP84gJAXhH7Ca4haKZxE0ETP5gDENRWTE5pQZTQ=,tag:EHuADc64/X+5RqNwfjM/8Q==,type:str]
    version: 3.13.3
