apiVersion: v1
kind: Secret
metadata:
    name: mcp-memory-api-key
    namespace: mcp
type: Opaque
stringData:
    MCP_API_KEY: ENC[AES256_GCM,data:z0sZx3H2bsgGMMx0clYWdL7DMJH5vO4TMjsXFVjuLJFJAhPdv34JQl2y/yuSjh0BSqgRrtksJotNhaDVR0xMhw==,iv:wEHsWti168w24E5zSJGBwVnv0E2wWvN5K4xxJk6fLho=,tag:AW4L1iKz7UuiqbnqRNNX5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdTZsQi9wSlpEUVRRbk5p
            RHh1dkJGOERHZnhPZmsyR3ovejZLQUVYeEY4CmRITXhDN3FXK1dJSzVpNUdwbzJV
            U0hpZkQyRmk1ekZ5UHJqV1loeWxzaGcKLS0tIC9WanFadDJyRGNVcmFFeE4zbXln
            YlZqaXJEaFUvOTNIczVHelZPc0ZSQUUK6ODO5wk5UHlBjmmsvWs1yV/e9gEwvFKO
            9wzrkBsU+Ar14LgqmlKnIVD56TLTYu9B5vUbOUzCBZzmbf7M4ZoodQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:45:36Z"
    mac: ENC[AES256_GCM,data:nCQKKEFesUjfNPLZDC8x9QJ8ikkzGmQCMVUEHiSLkiVJ1rz0i1YR/FiPcKYNDedS/hFgqHtBJ6BO2mI4p6Ni6LW4nHoxLe+i2zb+64bexPbSdNwj9vl0yIVXJAvqkQjekCngA4gyz3vS/8kqfvX648AB4bQ9f8EG0gvVFmxfFPM=,iv:eTSd/+CtER4LMP2Cyx8rc3I63zdCNrxpADcBQbT9HUM=,tag:EWqjohCRgHTZu3nBj358wA==,type:str]
    version: 3.13.3
