apiVersion: v1
kind: Secret
metadata:
    name: mcp-credentials
    namespace: mcp
    annotations:
        argocd.argoproj.io/sync-wave: "20"
type: Opaque
stringData:
    PAPERLESS_URL: ENC[AES256_GCM,data:/lLCLhDBA70b4glE4VAqBwGSv8zZ,iv:6ApReuI6amUqGhs3obgY6bOLtQih3h/kBSE1TZ6UV+o=,tag:g6atZdu0JSiVwgvtN7eoAw==,type:str]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:WZYs1UKtZaVLR7oTZT/IqQmbWGCv4/YhOeXPBTnkPBtqOnXppEwnrg==,iv:ZKwNDRM++OkMNf8Z3ltA11t1feHFu0i464ICJDrNk+4=,tag:DnU42A+Ab4PKDRdsDF1c3w==,type:str]
    PIHOLE_URL: ENC[AES256_GCM,data:27s6l87OjYy+nW0exWLQt3WS0t4=,iv:6ozaHl5JSu5ApcoYH8w6aR2C0Qh1u2Ho5yhpObmEB9A=,tag:Dyjsv+xxsuyxLULJ3vtfEA==,type:str]
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:QAKXrbVaaEI+TA==,iv:S2HnBd4Iey3aKN6mUpC4+PQKMCUwVNcQp6BfDs/AZVk=,tag:urW7fCNdLenGgeX9C4pdRQ==,type:str]
    MIKROTIK_HOST: ENC[AES256_GCM,data:/6j79J6+PFyaGf0itkc=,iv:UwttAUPvOVYso/GEmge91W2CQgj0HsetBDxtsvs5GjU=,tag:FMZuXUVAxGy515dPERBCLw==,type:str]
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:wUfis6I=,iv:FhpvKa1JsRKmGpZJER2ANgOLCW/BSE6ZL/uslJ2vLtI=,tag:/ePmp96xHR27j49+luQplw==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:Of6IfeYZCxTa76WuDnc=,iv:7OhnI/Hkjsm696zfJu9xz/MTiKuWvYa4NYueXOAvkzk=,tag:2fH9CF724vGiL21J8OmmFQ==,type:str]
    MIKROTIK_PORT: ENC[AES256_GCM,data:3v8=,iv:E/ngfWhhF4yOgV296aSM6Q6M3B5JUM7WqJ2jBVKx90k=,tag:JUdNEczpDVelzriuxh5f/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RkNTd3pVcFNEakVRMHdM
            S0pJelBoaXlUSEl1RVYwdktzYW1OcmV3d3hZCnpyWitvM202ODYzajNtMnVvZTBj
            UXgvU0VvTUpGTmt6c0lDL2p2bFAyOGMKLS0tIEswZitvS2hLbVFpK29NekZYSk5C
            aktVaG1EQXZLTE91a2tDeTJ0QStadVkKxZPARuP1kh/aqBdvOCl6qVaQ0RtwPlMs
            bA/BL571LeMEvMT5MfJFKulZIREDtpetR+Kyz713l5kb/cauPF2H4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T13:54:11Z"
    mac: ENC[AES256_GCM,data:OD4x6vq3pfUMM5A2wIAU9lOXx9kAsqf7LEPs/Xek+bZKU4tT9vpSuNn+F+ixaHPtVynB3v8rzHxcrxevAizTsrX3keb+Ytt08h26OU3x5l7bjySg9GdCrLHEANoCC8oY7r0ZzgBoiATs9WOSirKQPAba3zAK+eaYzBr/xc6yL2o=,iv:J6bv7vmHgdtbyp3uPSOBQT4nvZ1dUlLEEFPg/e4I+so=,tag:3ISGInOh6CeU40tLKaFjbQ==,type:str]
    version: 3.13.2
