apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
    annotations:
        argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:qTxd4HQQhXmc9qQ5eJo0zuMtVW4pErQWYWxRAc2CmSoliCu2LBiLJ+/lXEX84PvMF/X4svIG8EBT9+tAl53d4A==,iv:XNVI+6rIjHFVJO6LoFQMxuGnt8xdWtEmVKVPyA9hcHw=,tag:+lzoGUiybaSEK7qHMqxZ0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbjBBNWNhcjNPQ3NnNlNE
            OXo0VmFHQ2tzV011RVFyMFd2SU1MOEs4TVVFCkRTU3VyalMxbmNUVis3TEozTGVK
            VWd1VkFGM1J0RFBGZ3ZKR1RhNFJLanMKLS0tIEJNVkZDNWNGVElZd245VTZSdEs0
            Mm9oUFB5aS9vbU9jUi8yZkNSQWZaak0Kuo0wyBNxqxPSlZTX+4YXZYCwSkFyEaQt
            C+H2k/Jvm+toOfTCBFpItv3dc9vVRXEvQ5V+rKrkvAIwyadelSJxiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T17:47:46Z"
    mac: ENC[AES256_GCM,data:jzT6ptUf9CChh8GuyOYbAt8YHd/aVG/Vu1EjVrzP038eyu4xQPnTcemf+K/Lj75Zin6JFZZuqVpDuMMpFzHIUHRfRqLecGZMqEKbZUcfksVmsDF3qrB8p+p8TDHPHiQu6kKDpv1vLjk0fdFT5rRJjqIo5p9zt6eAnxiKOqTRt/M=,iv:wSEbaQgv81I6rJyTN2vCYj03Dzu+X5HCUIlfohNAEks=,tag:TAd9tQ7yJ57d2QgjTZfQ/A==,type:str]
    version: 3.13.2
