apiVersion: v1
data:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Wsri90g7ci7RBwiK24jH3CoT9GIbI/FLWO/ciQ+RX79SFSbUFqaLcfPWHUV2Z31E4oTo5BuGeoq6aX+gC9IuRkh6rDukbu6z9F39MdVkdZ9Opi8sUSjSwBA1tfN/5atMqmhg3mT5+Li354Y71HgNdhsgKFGyYHUV5pbwYopzZ30=,iv:uza6ve7HB+IWfsacbQjGBAJ4CpOuLlKMzxmXiK/oCGE=,tag:2N3cP3L8CEWVvvitDOOCpQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:Fbs/tyvq00v65ZfGCLNVelB+/2D0gebmwsNyOp5mqgY/X8JUW4BTZjF0Jf37L5V1fLvylwckdw0KKtuGrjq6z4XRXQ2aVA9K7uGRoKBa/e3jvo53yQ2bKw==,iv:eEp696i2rc/MwdGplhtkEB+UHu8a/RWbi5pZgaRV5Gk=,tag:A3JJyE2nIqTX7Y3cQa7UIg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:ZMU6brytuQ4y/Yy94060UDOKHPRNHKF+NO1hnVrdspBwuM9rSgxFyK+ospQjJpRSSHMfsYKukkkxRItZ9g52QKtdwIOn02Y2mRqCKX5lSAEFBeZXvS/Iow==,iv:Q/hYK4lWHP0vvjFEx7G6SjWUTcaSVG1AbR0w9XFiwQE=,tag:UI7zjypYU9zKGgg2Yxc41g==,type:str]
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: open-webui
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkwvYmpCR1g1ZFp2Vk5L
            T3FiMW5kSS9kT2IvbnUxWW5jdjZNbHpadEhVCnlBOG1mQU9EUzUwckxQeG9ORDRv
            L3F2ME1odkR4alhuc3lBZC9aR1pyRTQKLS0tIE13OS8zZjZYTDFCbXFWcy9NS1A2
            cE1pQnNZdC9YSkszYmpyMk5oamcvSk0Kn3rHbAJpOUoioTnSEDSpRhA+fRDPOefJ
            JS7uhbZgQK7pyghcSZAkeGrc05nuh7xbynflljYjnsnpIsiY8lk3qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T08:12:44Z"
    mac: ENC[AES256_GCM,data:2D+/LDKx2hN8KuqfAYAFbPfy2Lty2JWF0/rphshHJ7HpYhUP7uajwzvgdGqK08aWZJK6okxmeH6qpqHzKfBfWKV1cDBP8I4nJ6Tq4RFhlSEuRGVRX0k4lsxQ5xu6PWNM8weNBX2QymMpb4ZHmkrSGrUg4m1TRSgdaCW+k2OdQt0=,iv:qqrTm4NmKiXyHHAwYimTWB2WOwWGrnDyNT+jPKm3tcU=,tag:H/uhCz2Qs71cQFwenON5rA==,type:str]
    version: 3.13.2
