apiVersion: v1
kind: Secret
metadata:
    name: openproject-secrets
    namespace: openproject
type: Opaque
stringData:
    secret-key-base: ENC[AES256_GCM,data:F9Bj6Ipc3KVRU4XvgdJDOvcQXc9/UVDtEnf1SJBmIk8/LRPRb+87EdNq23FdTdnEcTXf55ZHI1LVTyRY/ktFP3d5qSGWTkBn7Ps7edV5308OMYW9nUUHpToNAStd13Nih4ZvoIgH/xZWOG7GDnD+vEBYewfKCKh3i3DTU38Murw=,iv:xnR6ueg17ArnA2XJn8CnXjGdkhWnU/xuhQ1JU2e+wVc=,tag:tnSbK4U4x/d8YOIa6gd6ow==,type:str]
    OPENPROJECT_SEED_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:5Gbn/DyX5n8njPawcz8kPeH0jqbfYnfY+kH7rNTzD+4=,iv:sUKV5Q/UIP6pwGIGTXCQLfhpOIW+fq/swA1kOaGwC2I=,tag:7cNX3Hkx49BSKAgzPYscaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbzVocWdsVkJhQ2NjNnM3
            TGd4NS9Zd0wySHJHZlIyTnMwOXgrM3NVdm1RCjZhdnNEeWNuRlBiSzVFVFhXKzU5
            RDBodE5JTzlJQUNBKzZPckRib1dsL3MKLS0tIGJqMUhTdVNzRklrV3hXaXRwNll1
            d3B0dnErc05iSGZGQlU0SHI5cStPZ28KX8kTWXwR0Fc8BLjTGVzlH6Q3xgitwLjf
            UfqjBYBeI3gb/bwjTPcwCZw7KY4VttcCtnIoevBM33wSU/KcQP3l2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T18:07:05Z"
    mac: ENC[AES256_GCM,data:r8kSVA4+OYfS0JBAhI+iu9bh+51Z5DGf0AwpF2KCZeTuailjMRqy05WMIxllPVVLGkK1p/msfBCvdkN8E7p5I4hjUOZ0ucVuZ9foIbC4FCIBscUqy2zZKPC6EywSDbf1KQTBU+65X4+t4tO83YqLx9aWaMorYGC0rN3K59fGNYk=,iv:GjUCa4GmRkJllKgvGFA0HgvzxClS2cyNxDq2xmV9jgo=,tag:RZthNnJY6kJygwwLBTWTPw==,type:str]
    version: 3.13.2
