apiVersion: v1
kind: Secret
metadata:
    name: openproject-secrets
    namespace: openproject
type: Opaque
stringData:
    secret-key-base: ENC[AES256_GCM,data:F9Bj6Ipc3KVRU4XvgdJDOvcQXc9/UVDtEnf1SJBmIk8/LRPRb+87EdNq23FdTdnEcTXf55ZHI1LVTyRY/ktFP3d5qSGWTkBn7Ps7edV5308OMYW9nUUHpToNAStd13Nih4ZvoIgH/xZWOG7GDnD+vEBYewfKCKh3i3DTU38Murw=,iv:xnR6ueg17ArnA2XJn8CnXjGdkhWnU/xuhQ1JU2e+wVc=,tag:tnSbK4U4x/d8YOIa6gd6ow==,type:str]
    OPENPROJECT_SEED_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:5Gbn/DyX5n8njPawcz8kPeH0jqbfYnfY+kH7rNTzD+4=,iv:sUKV5Q/UIP6pwGIGTXCQLfhpOIW+fq/swA1kOaGwC2I=,tag:7cNX3Hkx49BSKAgzPYscaQ==,type:str]
    clientId: ENC[AES256_GCM,data:+32DYqPfqQEGSK4=,iv:CG/3Bdfo2JXjUiqzUVok7n011EWq2hyqLscK0EUYI2E=,tag:/zG3ut1TkiCKzXUSQmkiyw==,type:str]
    clientSecret: ENC[AES256_GCM,data:I7dqe30bjTVInkl8tmOjtZzH1xAmbk1j5TFQyh5Ud5GfoH0C+hoObLi1LjktnH1aIz8xCfLG+82xJ3T+Cz4K5Q==,iv:kgckJ6AJAMjaPVuhYaAbexfS7C7UOM5jKmpdcSytkGU=,tag:ZBqzNTPqI3jc6vAyozqr+g==,type:str]
    OPENPROJECT_OPENID__CONNECT_AUTHENTIK_IDENTIFIER: ENC[AES256_GCM,data:bJDkqLCWRIe4HyA=,iv:jniwCr4ib7fNirO7zlbBtogVTxku8hDDrOzW+v7sOMM=,tag:G8iicQf3CBHXmSUg33jNig==,type:str]
    OPENPROJECT_OPENID__CONNECT_AUTHENTIK_SECRET: ENC[AES256_GCM,data:g4L6ZjUkJ0Tw39YlTP4dYC8Zx4CckAW+8ViSKnpc/ROUFHjYRN3G0l4cOndb/zXUaeMVwB1IHxsFyPj5pvZjnA==,iv:4XunsdrvthGKEnLimPYcAEzzS54eXgQpmw0toiwNZDE=,tag:uhgt+nRzBxLVydc5rHogRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbzVocWdsVkJhQ2NjNnM3
            TGd4NS9Zd0wySHJHZlIyTnMwOXgrM3NVdm1RCjZhdnNEeWNuRlBiSzVFVFhXKzU5
            RDBodE5JTzlJQUNBKzZPckRib1dsL3MKLS0tIGJqMUhTdVNzRklrV3hXaXRwNll1
            d3B0dnErc05iSGZGQlU0SHI5cStPZ28KX8kTWXwR0Fc8BLjTGVzlH6Q3xgitwLjf
            UfqjBYBeI3gb/bwjTPcwCZw7KY4VttcCtnIoevBM33wSU/KcQP3l2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T07:55:28Z"
    mac: ENC[AES256_GCM,data:P3GA6RQlbD2/sp3X4yLTSJM0ebm6ynYRteaElItp2h5rX6LYXz4zG/c3aAOzTSshWUzmixrDLy/9lRqlxxwJwy6iCS91wKLDLcFOiyyg7/tiEfXayxSFo9osNKjj1J5wm3MTP/abbn8X/+XSBHCyL91b8Hbecdw/1I44B+MW9q4=,iv:PAeYJbpXZjqfQkCcqj4qNA4bLUUb8yprdm0r4L2BBaU=,tag:kBP7vQ6R1571nYuo865o0w==,type:str]
    version: 3.13.2
