apiVersion: v1
kind: Secret
metadata:
    name: openproject-secrets
    namespace: openproject
type: Opaque
stringData:
    secret-key-base: ENC[AES256_GCM,data:F9Bj6Ipc3KVRU4XvgdJDOvcQXc9/UVDtEnf1SJBmIk8/LRPRb+87EdNq23FdTdnEcTXf55ZHI1LVTyRY/ktFP3d5qSGWTkBn7Ps7edV5308OMYW9nUUHpToNAStd13Nih4ZvoIgH/xZWOG7GDnD+vEBYewfKCKh3i3DTU38Murw=,iv:xnR6ueg17ArnA2XJn8CnXjGdkhWnU/xuhQ1JU2e+wVc=,tag:tnSbK4U4x/d8YOIa6gd6ow==,type:str]
    OPENPROJECT_SEED_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:5Gbn/DyX5n8njPawcz8kPeH0jqbfYnfY+kH7rNTzD+4=,iv:sUKV5Q/UIP6pwGIGTXCQLfhpOIW+fq/swA1kOaGwC2I=,tag:7cNX3Hkx49BSKAgzPYscaQ==,type:str]
    clientId: ENC[AES256_GCM,data:+32DYqPfqQEGSK4=,iv:CG/3Bdfo2JXjUiqzUVok7n011EWq2hyqLscK0EUYI2E=,tag:/zG3ut1TkiCKzXUSQmkiyw==,type:str]
    clientSecret: ENC[AES256_GCM,data:I7dqe30bjTVInkl8tmOjtZzH1xAmbk1j5TFQyh5Ud5GfoH0C+hoObLi1LjktnH1aIz8xCfLG+82xJ3T+Cz4K5Q==,iv:kgckJ6AJAMjaPVuhYaAbexfS7C7UOM5jKmpdcSytkGU=,tag:ZBqzNTPqI3jc6vAyozqr+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbzVocWdsVkJhQ2NjNnM3
            TGd4NS9Zd0wySHJHZlIyTnMwOXgrM3NVdm1RCjZhdnNEeWNuRlBiSzVFVFhXKzU5
            RDBodE5JTzlJQUNBKzZPckRib1dsL3MKLS0tIGJqMUhTdVNzRklrV3hXaXRwNll1
            d3B0dnErc05iSGZGQlU0SHI5cStPZ28KX8kTWXwR0Fc8BLjTGVzlH6Q3xgitwLjf
            UfqjBYBeI3gb/bwjTPcwCZw7KY4VttcCtnIoevBM33wSU/KcQP3l2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T06:54:26Z"
    mac: ENC[AES256_GCM,data:wD3ijfRVqGcMNpsEha6l5pDybEV5xkhArkDsdDxAIiV2lsD1wJ2vIK1lbz1FNaMT/LXQIRI0tgCkzpMInW1oSFcKQs3JGrbLxmIu/Qtbd5bCysITT+y9kQ9zSNVtiTwcP9DwwQgwjwM9W/1NNJtJsyHCtwc7WHWctJ9ut2y6RsQ=,iv:qEoGe73IqLc/PJdZiZdjqAF7c2LLO5PKoPwRdR412Fk=,tag:oYXHMK6n9i47/ni/hD9MSg==,type:str]
    version: 3.13.2
