apiVersion: v1
data:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Wsri90g7ci7RBwiK24jH3CoT9GIbI/FLWO/ciQ+RX79SFSbUFqaLcfPWHUV2Z31E4oTo5BuGeoq6aX+gC9IuRkh6rDukbu6z9F39MdVkdZ9Opi8sUSjSwBA1tfN/5atMqmhg3mT5+Li354Y71HgNdhsgKFGyYHUV5pbwYopzZ30=,iv:uza6ve7HB+IWfsacbQjGBAJ4CpOuLlKMzxmXiK/oCGE=,tag:2N3cP3L8CEWVvvitDOOCpQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:Fbs/tyvq00v65ZfGCLNVelB+/2D0gebmwsNyOp5mqgY/X8JUW4BTZjF0Jf37L5V1fLvylwckdw0KKtuGrjq6z4XRXQ2aVA9K7uGRoKBa/e3jvo53yQ2bKw==,iv:eEp696i2rc/MwdGplhtkEB+UHu8a/RWbi5pZgaRV5Gk=,tag:A3JJyE2nIqTX7Y3cQa7UIg==,type:str]
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: open-webui
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkwvYmpCR1g1ZFp2Vk5L
            T3FiMW5kSS9kT2IvbnUxWW5jdjZNbHpadEhVCnlBOG1mQU9EUzUwckxQeG9ORDRv
            L3F2ME1odkR4alhuc3lBZC9aR1pyRTQKLS0tIE13OS8zZjZYTDFCbXFWcy9NS1A2
            cE1pQnNZdC9YSkszYmpyMk5oamcvSk0Kn3rHbAJpOUoioTnSEDSpRhA+fRDPOefJ
            JS7uhbZgQK7pyghcSZAkeGrc05nuh7xbynflljYjnsnpIsiY8lk3qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T08:17:06Z"
    mac: ENC[AES256_GCM,data:yaUAtuMBb6PUqTlyciliEG3AKzYz3F6Xnn2WeCMeSzQS4ceTw5Ij80oznfulCA1J6D5vaMYbhnxsLM0TQqDtAI48kfPz8YtagjXrRxmd11YK7cPX4H+p0PJKbjYty3/k0Zj56E5BJH+Gh2pgYwGrQtJkJaQ4A4EHPmPEcC0Dg70=,iv:4mp/yskpvYZ7Np8hDf9pP/WrcJmj+BEs8MeND8EpNfg=,tag:Z90uvCEP6rQEsZ36Zh7cqw==,type:str]
    version: 3.13.2
