apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: outline
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:qUwRYLB1UVm787rrURXVwHnjmAVd15+9pLVzYfWs6yuzhqZge6IsXmBSoX6Qzpt3cCKlnQRWsqMZ9lwCfrVcBg==,iv:afIPBBXKl+1FprhR/BE+jJAXEvJTqtYFckmobZeRwzU=,tag:Ic2SUmfTq2ecIG+H7nvw/w==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:iF0xe4rGcYf2HwjntfL3ZSumltNBdL8D9W3f13LEmyVpr8F41/5Ws1pCVTnixKCbM/ArtExybeiFaSMvm2qrog==,iv:dC9EVcBHlCn5wFT/J9Rokte6Vw8fkXqPbz9ooiFySCI=,tag:2U1+I+CxAp6j5H3bys+rCg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:GltvueYMJpdoGZrPtn0d1PWPxULLg94qTNZy7hBxxmGVxE94+4bA89KFVNLrEXd/jF2/+6MP8tm+Q0ZkeSSZpA==,iv:AnhOpOLvWWBVGRvAaF+NdjX+5C7cN+xwc2/55qgkfNo=,tag:kcNRKFzjSqo6nEI3xCTStw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bGxRc1dlYnBCOExTaith
            UWtnanlydDlGRkdvWklLaERpSXVBR29DbURrCjVoVm4yeDRZeDE4ME81UHJWbDhs
            WE5SR01jQkgrRmZ5QTVhbDU2ZzJaa0EKLS0tIFhDdllmaFlzcURWT1FzZlBpaTRZ
            YlB5NlMzOXJCMHFnSXlKODVKcFFHcXcKBAJgagfpdxNgZhyxKgmMRhjI1GMPt/f3
            3/XADoxlqimiE1I1fDOsnJqWiNsIsUCl+BRExKb1H4iviJclXimTAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T08:44:29Z"
    mac: ENC[AES256_GCM,data:/9tMjx/WiVHSnpXT/Tt3lFIXdQLxH+t/uR65FlMYsLsTS6h/+byt/jgEZ7HxQrw23ehlEFdJf5DH7v1G9OkcqNWI2yrkuKbKLCz1mM80pM5UI+IuebrT3TClhtgwnjqZEQwTSAexKuzu2kaE9CcDIQbT3k70zrQTYY/UAEm3AbM=,iv:Z+7SivHg5VxqenKLxQhf42+6qE9L92suXriZckkH9Rs=,tag:IIaZILgnjNz6NDQkGD7Miw==,type:str]
    version: 3.13.2
