apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:56t/QBYrffDcmwF0uTTvwglCMGLdHQintHhDCn2BxqKvY/uIcpn+aCgyEw+Oz2feRDnt/LegLuet7hD+8b/etYMwUAZLyrV+ed2bmCcy3EqD5yU=,iv:cDKDjRVMjM4jQjWIeeD4PhESJf/35rQUg9pEW0Wc4Hw=,tag:ICJvzfivpIt/vSeQC1exGQ==,type:str]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:bZMDoAzyFMy54A3z0n/aHjpty0C1MTRnUb+sBWknv1UiVZJY8WTPkkgKzTo5FHzBLKVhAVeFeu6WZgooxcY4uFb90mCiss097su1j9kfQczd/WJjXh5A7NNoGszsvTq+,iv:uV3tD8PGqEiQAdj5fLgd490cRRYukgnorp2Psx1fgf0=,tag:kcIgWHO1DoUC02bTsa0G/g==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:7sHqlkDUMrup8/tQ+g652PdLv93l+n3wXdm8D1pgnx2waF65Tq62W9wuZQoohoLElv7QG3vd8Vvvf7VONofk9IeyNnoaggmH3XABuhESk5xPple6V61BcHfxb87adzVQBFphhBNqFLLMjClWpAwWFBFbxka4oxDjMba90Zupk43YToiC24eTpkRt5KnYX97gLnGDOOw5RlgAL3LKCG/VNuEY+B00wtVlaFa2VFzkWx2FsBBztEjLesQ0TOskkLQNBBI2l/EdoW0GSJ1Jt2tPiUVt7hHoH8/rpHssq9bqliduvxTJW7faPVMgIkYPYo943biIN9r7ubFL9xQf7HYJi8qUz6Uw4h9s/g6BY3fbplXCamAYXNIpyVdli0Bt9DT5vos1ZrbLEFy4PO3U4QVONNXD+O7z17kWqLma4ZP6ne/7BuL3qyqv,iv:AK37uS0sfBlo0GPrIWlD/BKCU1zRleQyg9pcfhqKZE4=,tag:zvvZtvd41cXYaSRKqAwHEw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:JzM8CHKQUV5tUfWpfH6HBl6MB5pCV/CTYikDVKJbqE4u3P3GsRlo9y5mMfxT2oncF0qfOqkaQiFEfYq6+AxnJA==,iv:ejWXtB2qtXKQzRwILiXyZKEpNWJOq3gtefYqmrrGvIE=,tag:E5jvRVAItTUrUvhsccPctA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSXArMXZXbTZldUtFT0R2
            T1hMQUY0bXFkb2FxOXkzRUNpVTQ1aW12emo4CkkyQkxVZFhZUS9pNUQvbVJ6M0cr
            elNJTnhIZTJXa2tidTdyUG5SbktlY3MKLS0tIENvdzZBTTJWemJiUTFmSzQxMlU4
            UkpHUTVLNDJrZHNoa3EycEV3QW5Ta2MKcJtQRz0n/Q4qrB7BLOIBMT2b5PKxnUTn
            woioStdJhadSY8gxnFH6SPmv52RFP8z6PIeSCGfBQbfmCJ4Sq617hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T09:52:36Z"
    mac: ENC[AES256_GCM,data:rdA48oA9lO8DKiT6qwTYhv75z3xamx4Mqyl229vELqAyCuAAPz08sA04fEokEePqwqzVikb+Rszm7UL31LQCZLvCf0dc+hYUDvPySfSYR6nMcg+nXnIW/xuonDU3PAbzV2ZBHf7uGf2WBAfC9v6SwtIX4Fvg/0B0VVCb2iMAzXA=,iv:6UMW+1zTAh7yBZQ485Kl7bWHfB6palhYJ1+Dy73SLh4=,tag:12jpbWnAVtMlFqFjFnU85A==,type:str]
    version: 3.13.3
