apiVersion: v1
kind: Secret
metadata:
    name: seafile-secrets
    namespace: seafile
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:brKUbKw0b3JorQgSaOcXWZSEQVCvHS6Ik3+SPO65O+om6rXsBRSMXH51uMcg7FAY,iv:eEBP5eaKi/ywJbBWTzaWtBL1lhNHFnCjZwET8/o6wD8=,tag:BMc3vbi7uywDpuCeBLeGbQ==,type:str]
    INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:I9FP7BOiaqaZ98KjjLGQ70t2XiUPSFG8V9EMqbCNQ4TlXpMjlcsrSiXbXwYYux6g,iv:nGLGhLh3hmdMish3eX7veHmpA18y0S/+YUrLDtm4s8k=,tag:+dS320Z2NxGOmS8ZrsUYeQ==,type:str]
    SEAFILE_MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:TBDGzRAJTrUD/fVXt6TQqbkMYcfdhCEB20cVTX0qYnMwXIXNvIV68Ggu0d1cBxdc,iv:NEVg5RECEaO+I8IiJ2iV2DoopEhYYHwanbIxD20fcuU=,tag:oAPXuiwDcd6IKk3n8B9+xA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:gnWE25JoRE4FJ8jd5Rq36otwpm0j5wY18Dme4tvaeOhBQunP3/lgGHuD6zZ8PZlX,iv:KajLtm2v0JZBhpnf3fo3Trg5aNKqr2HoWXcKrKCuihs=,tag:ECXnGxIVx94WcLasYWW1Zg==,type:str]
    JWT_PRIVATE_KEY: ENC[AES256_GCM,data:f9ouQpN7DLrhGZQrW5ab1nPQLFdz0lzWkaW8PMa1/eHyYYCS9pWqdVZ5Jh65EZS8/amEweaxMIPmS9NwwZ7dwQ==,iv:xWxtU+fYlKgjAAgEuxLh8V1wukzmP1knVMPWJeOp6/8=,tag:5waHRxbMhK8spvIWJuW62g==,type:str]
    INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:jo6oyGclAQ2YKjlRnIvvWPsQWmNhZy1Tk8g/IE1pc9c=,iv:FkwnweSM2gNNEdFTnHoStBLFI5Pe1sxca+Nmq50FF8M=,tag:0qphP986Er2pfrxkP5kvLA==,type:str]
    SEAFILE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8R0sBbnWCJCC0yP9jILNy0q29duKBoWNNqCTgv3lf01faIa2cmAZJjH8u1QFGa2eaT5zmS0H8+S6Pq/Anv4tqA==,iv:wEXCzzdStu/q8CQoWJ7Xdbth0Tcm/lM75TNyCO3QtHA=,tag:oWfofXU0Xxusqa8XBigL5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeVpEVkdUZFJJdXpzYjFm
            b01YNFFPT3BGVDRoeXNpc0ZDdTUyLzl5TjF3CnMrQTBZL1hJMzJxbE50SUZXQnd6
            ZWhKMEduMmt1SnRndmRLSkJFNktJcWcKLS0tIFZsSG5TekxaVlp4Q2ZUdFY4YmRx
            TVdlejA3UXN5TzFjM3hDQk1hYjFBb3MKONmku0yNiqzr8fZ9CH5vzpEFTgyWEvnU
            8LicAOMTWLYI6cQxYgb7MN/+drM3tgEbVMU57D27+TnQxEJgcoP1XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T16:40:03Z"
    mac: ENC[AES256_GCM,data:KML6xULtll6nvKLk8a9nZZCeMG7NKtyfTtiRSmolUjv4mEnAaoVXWF+GSIjbb8BQRKZaIpZud8+FQAWPLGN6PcZgAhUcMAGzgRQYTJnDApmkcwjEDvP/G5I1byUFKFeZHdJxK7RyE45JdQGZZpjnBJSRwqSP9r3NDqZhvENWRlI=,iv:jfxKcZdG7XGuM2piMe6aW31rwQnZiDLL+HJa93VHp8Q=,tag:hJOIRUa/yyY3ZVN/Lob46w==,type:str]
    version: 3.13.2
