apiVersion: v1
kind: Secret
metadata:
    name: seasonvar-jellyfin
    namespace: media
type: Opaque
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:l7Lj83So/2Mvzsq6ucqF9Pi0MI2BSUYc00NXe20i+6I=,iv:irP/ejwYpX9amjMv08whz+7kQrbAk/OwUJLcQZo6dI4=,tag:Fqxx+Iqd/FkvU+AkTv6F/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySjJsckNQRDJtdSs0QlEy
            MkoxaTlGYUtoZnZkQ045MUIzTmFkNHgxVWlJCm1hVzVVZFFqTU04eUlCbE5aKytX
            QThDWE1paTIxVFRFN1dQcTVIQm5WdUkKLS0tIHl0VWU2SDdoQk5NZVBPWkhIME5J
            VGZaTmdGVmJlMFljWFRZdEJaaW5hYnMKpdRL37YXKiNxkZhJI4t0kjWdJG/vu+Iz
            KAy0Jc+i80XEpDBIHsB75ze6gSMQ7Ke8TnX0im7UyCrWZU3Wm1TzFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T10:26:57Z"
    mac: ENC[AES256_GCM,data:/LYlbtRHo84MIfn4pWClmJGK/UiRsmXzByo9V6yFL29PvLMhVoNpjrS3CqDkQRIaC3yewz4cmAOs4lGzVwQz56Nz6zuw/aCKqLbZl0wJrBtnYtMtpVq1gQYK81PoYC9Rbr+r/TMtkIaKiO6yiTyl58bwuiwlhFFzSKdSa3MxMkI=,iv:NWgPLM6EYqCKTUbeUvQAj2Kd+b+Ujq9GhW9uS+ffxcE=,tag:qOIvgJTm5enOq8VH0fBkpg==,type:str]
    version: 3.13.3
