apiVersion: v1
kind: Secret
metadata:
    name: ghcr-vasary
    namespace: media
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:F/6Qjbl/6A0ZNGZOFc9u3JoiXg+hl7ihppvwnMiGpvahJkB25f8kwi02ADZlSDyzt5Y8dWUV0rZOStwvUkPioFe+3ZzdyS5qrFHnQYJ0eVL5Zm2Ad3ld6fFBv7ftcPq1nDhwS0sJMqy1+yFqhdgpKRQQCUERs16nTs6ZHNHv0iOSTagsq3JPH/q+gbrizSgo9S0aHWSzzci7vuOAeylEnT9Yc8ULkmVRdhop,iv:s8h/QvjqY+G8D+ZHKTHHWYFRqpTuMt9b2jytrHKaPf4=,tag:fhBWJvQs9vA/5Z5tQvENfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaFFoZC9neVVJc3ZZclFu
            TVlwVjJQSHBhTlc1TndzOUVXaG1JeUxGUW5ZClNkVkFYVHhVV3lCb1JWcnRTb0dF
            ZUpnajBZZnR1c21oU3V6bldUMk1sbVkKLS0tIGkzMXN0NkdCdVA0RURwd0I0a0RP
            cUZLRGx0MXhIV1NqWnNhR3VqN2RxYXcKEClKOsaRu2Rv17wP/VJLYCYsJTz7QG91
            w8k1xo92t5hz3y0bIvqG0Tda6NzmH5EpL7widjLIpoMWWkCI9n9k6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T06:25:08Z"
    mac: ENC[AES256_GCM,data:3XzeDAVpOR4XR/pkMgUDz2wJXy6SpmnPw5HwuPzEAMIuJWz83kazLqBfLPqCSMm3/TYFQTC/tpfwxtyc6AT6lPb6jHna8NmyS21DFZoQJ3L+/IjWmBtcCgNWXpc0VBTPAbaMVUq+bqtcGKoPcE6iKO6rNGyACr9mlPwpM0VnQ1g=,iv:dKbOqKNduzcZfI12CXYr+h54T/Rmu+w0ljKkN6KhiVk=,tag:nVlzdpQC/G20AWFSUEOvNA==,type:str]
    version: 3.13.2
