apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: authentik
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:31D7p0rzni+KGjrpfQ==,iv:m+izmkM5o5uqHcg7ndD4K1gZNgEVT/uCwb4wc1p4ids=,tag:Xpnxj4UF8G/BRHV6rI31AA==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:WXATaA==,iv:Z5x6bUOk6tNdFz9iqi/tZ1XmGmf4oSI7nCiiw9UxJRo=,tag:y8vuSR5cVi75f26QXuyRlg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:iZ0XK6Gd,iv:MP7wLFOU2bBz7szIe+CU+OS2NjBpl64XxKKXuUBaRI8=,tag:R5cMYhgzs1LLOtGEabNHSg==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:RSb8u54u,iv:moci0eauR9uHH4H8aZfS6Y6+OssIyY7AU997iqhkHFs=,tag:tPXbprak8Ft5fKEE/ujl3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: immich
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:DHwi6IS/lEHNjS0ZBA==,iv:Cs7IEeOQXiCGB1xOPNUAA5QKrp2R4gt2IdT9XQ8IsnI=,tag:TD/tklMxUX6FH/OqX5KUZA==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:9xB8zA==,iv:bWOBTZtSNCqo3iiswoX56+oveWRRybhAUmVdGsDptOU=,tag:9PY4yoFbVBn6wPK7xEaVeA==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:lZiGqbaq,iv:j5AD8PSBlOVkv2VLID5RIV9ykRW+CmjMiUxPhjoEXnc=,tag:o4ZeAtzU2C3yztlQ3HCr+Q==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:JtSZVxz4,iv:FWqO11ivM7oTfIhWlofqmlPWV0+mg9wFq8J3rj+cM+A=,tag:ltBK1vjb2IHUIRyUfP9xQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: media
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:eJxmclypuDxhzuoglQ==,iv:AJi+gaeTUghA1g4q+bcyk7KzFI+wwxMjXyFw744og0o=,tag:YuIlGb3gKSdyXPF8+ELYQw==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:KepLGg==,iv:BDG6FZr2nWZxTCiJ2oS0QnToFsWbraXkYsbjudxb4cQ=,tag:OiHqWTdDwULKuDNujsdRMg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:scTahD9q,iv:i7N2N8494TxII4dqBsPb0UTUbZISy9uknIoWMRDLDzE=,tag:shI9tfQFk/CjWtY6GVBfgA==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:Z23aYwJ+,iv:brPvGgMA/3KUIy8tMA15SDwX8zxZdx4/+D+poWqHNcc=,tag:UICoKJ7Ui4NJ5ekU6LeHuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: llm-proxy
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:1GSUQaUO9GmwdhLq1A==,iv:CIh2kC5r5PSomdOUVTn+wH/AAS38/g6+/iorBAVyjYE=,tag:P3eAzw/+P1sIaIEp2V276g==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:LcWVtg==,iv:Kphe0xEpJN4jHTy/jWzGEpuJeblxG88fIVGJ0s9YIqQ=,tag:N2eT7b+X9IbfK8yvXZXU8Q==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:MpGmtLOY,iv:BFOT6/cMzQrTAjZDLnt+GnEsstr6mRjWLEC4ZNlDeEI=,tag:lMNhjLy8Pc469PtFu9jU9w==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:k8dvAKrA,iv:SHLmYGIrAkMhvimSFjpQwjfjeQfXvQEQBv2i1Tlt0zM=,tag:JQDTvJnQNKMji+C3YroQEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: outline
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:AdSByxxYfvgePVCN7w==,iv:QIkQvB2XeULjv6IVqAnS5ReyC2Ete/FF3Ba4HEMwGWg=,tag:SVkVhayzteVw54LvFI4Vcw==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:6GJtUw==,iv:HWevIkqpP5bQHYwa6HCkMVoK6jtOfSKxaXPLReXuKKA=,tag:IxCOF4u64u9H+P0dGmDbiA==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:u+uufkVQ,iv:bm3tcoL+NoziQ20bK27x3/nCRghhzXbQQdeuXOfNmLM=,tag:ioN4sDukz9N5lCEy4FDlRA==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:YPLFujfo,iv:JjqODwpqIsjcOMorBSOIXfEWwRG47reypeLG/3nJVtQ=,tag:tIjoxSkUQgnM3en/THDhfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: paperless
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:pGqVz6+XdRxX5LS5mg==,iv:qNAQ5ZFxqKQnIrr/ABRsCZ71hpthqp2B1Th8vl4i4Wc=,tag:z1X40JLm928gthtGQU0Nuw==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:mnyNbA==,iv:py/0KVKcXAHkaXOyfsI2Qa+gErpZW0/uyUVkQ5GAiYI=,tag:4NYy0Cc8jXTEHdXlKyLKIQ==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:TXiVuEYB,iv:ZykrXFNtNL8cmDHAqpg72bsmtPKRc/7nRBdp9v4oCKw=,tag:gknPQ8f6b2d210CsxOuAuw==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:w4F9VbPO,iv:nbyaL3YaRrXDcx5W0Vym3voE43CEwFrVtPxhsNM1jFo=,tag:lL6u4UudCK5U88SGl6pmtw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: seafile
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:F3kXjZHiK1fTnISUOg==,iv:0iY1QOFUSlmZGiLNqV3N5rIf3c/abhGgUf0efbsA5Fs=,tag:QsJxof1X4G7BgacmFWQzhQ==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:bgTfNQ==,iv:Qg4cQ40C66pMi17tXZ7BvZ0L6NjVsE/9uGp42ZWYeO0=,tag:tg9L/Z7Uh4JiEvCuvM0dow==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:OWsSSQ15,iv:HfeJ9YR2XB6Yh63ioo8PB6xtEABoUIyruu0e+fG01rg=,tag:DDGn6dpl9ztngCoqqaRenA==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:tY7y5hA2,iv:J9AFfgG7v5PGPLGFkgVa+gqDfuYdAXODfJAc9AYwemY=,tag:Zt/wITlF0LK6s8KuX9aZKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: vaultwarden
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:pxFFrlqUSlzPUkV8vQ==,iv:t3nGylpqjmEY2mjavULc2sixcLxOXZFH4MLIeWKJkJU=,tag:hsoCUxn8TgScuWFHbpoNRg==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:RPrsEw==,iv:88u3v1b10bLDlneQBLv4lMaG+rfUWw43DuYscTZ7Y+I=,tag:PaMMpHDdmSRzu5AhSwr/Lg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:qrJP7KqT,iv:HiNuSqZ5GPF5gdWRmDcZrkjlhPkWcozeEr7u1gdf79o=,tag:HPaJGqO7oPzBmUlsP7wbHw==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:zDZBMvZw,iv:/eqEW2Ke5s76YkWCHEbPrOokYH1GjmdKGcCPD6uGp3A=,tag:ka7Me1iHWjEuoYN4Eh3bjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q0Jha09pSVNqb2oxTzFl
            UW9DOWhOckNHZGpxeGx1RVc3Umo2aVVtY2hNCmpSVjlzVTZadXAxanpHb2FtbU5r
            MWovYVlEdjFxcjNMQTZnZCtjOVh5WXMKLS0tIEc4L3JaTkZWeEhOeXBrZWZWMXhk
            WWNuaXhua0lkMHc1Y3FTRjdyQTJsWEkKJBUZdCykVFDJ0A7Vv2tTp59ynozGHeUO
            EHOOD69Fz+1YHQuM2So94/som7JbB7isZfutUiwPXkh86FhzMs6XWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:46Z"
    mac: ENC[AES256_GCM,data:s03tDrarqjhAduEPr1N/iQuUxMfKV69kcebh0EN4lr0NnhjTadNol3MiGMCv8FQhP7hLswrw2GzR7wLhHj6hmUNILyv/T/aZSGa3LUJ/s1hJpowYTd3zDmvLJJFkIL851LAOmjcJ9lfqxH1yyg3ImZ1peShdGLw/45CU0tmsD+g=,iv:cWcjg1feWtuDUl8FwsfRRIY0swfJHT2z3lP5Lx5X/3E=,tag:eyMjZljqq9brYSNUFQ8LGg==,type:str]
    version: 3.13.3
