apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: freshrss
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:tL/JSwEsnhDJEdaV7Q==,iv:DPBFbRNAmLXQb9Q5+lCCkQD2uxbojQpVrGrvtQsvzcw=,tag:Ey+FQ49MMChxRy4vhMCtKw==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:uIW65w==,iv:a8csfq3QsmNnVs9DESaA2BIivjlihuMSfUWkcPhN2oc=,tag:FB/zeM5GZak+7yZeWytRcA==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:cR+vSLNv,iv:Yr328nW05HiWaJfG3baUisGakItzPpyXxFQ/4iup0sE=,tag:afdy8oAWBnXl8N1pUBQk3g==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:TmyJT1wV,iv:SRwD69VdADraXd6eOLWrPYQ/FprHF6eM7WOF/hRBfaA=,tag:wr5bJ/ZXH8B20kNbxX+ScQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRDhzN1BEbGFTdDE1b1JI
            TDN2d2dQNkFORW1zK0RYR0o3MURqYm1jVVc4CkViaE1vb1FBalFrQW52SUtKb1Jr
            bWNsZHF1V2trY1pubUE3UzhGckhTZ0kKLS0tIFUzT0hXQnMwdnpWNTF1MmxFU1FN
            U3c3WXpiUzVkK2VnbENyMm16K28yZ2sK3Kk/XwPyynT5C+LpK3r3VzOPsof4Xi75
            e1UOVTm35vRPwqGqRzc9404aP7AO61YhYgLNbOyfmpBFsMdPq6tdRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T19:18:47Z"
    mac: ENC[AES256_GCM,data:PNLvbfpMBJTSlkZghZPZG6WhiBFmDYq1VPsh74jqW+HVZXtxuFzMd+YhXbp3QYp40tP5JdP+5OJOKMoTQfI9xU7Ij7dqGumkvFv/ih1a4d/r7jpFoQm1fzL34zP5cVTFklRiwz9FIWtHhaiuATlNwEBvYZj9mcVzyGH16QZfONk=,iv:x9FWAnl8z9+w0IlrLG2/FQiXzhjJMr+1EOnl81ZBoG0=,tag:9RR5rZrn0VDdoQnSXR5VdQ==,type:str]
    version: 3.13.3
