apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: freshrss
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:/ovuSOj0p47s,iv:mXA6owsOsUx6BVF33849zZV2V7Akof7EgaFZJ2Gbxy0=,tag:FrOYgEaT2QuRxpRE0nhOmg==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:ktBCiQ==,iv:WdHJfNQPj9OZzHsv3ryVE895+WCdhiWjZw+lwvsSAEg=,tag:DgVrlkpscqWYaCjASjXZYA==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:1j2lBib0,iv:tffsTDECLG+Mli7XjJVLW/dDhTAM68XVZXfhBP5pA4M=,tag:o7cQU6EETpBlZxMjZzZrLQ==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:YpJKGysV,iv:q5Q962aas6cRa7WMM+l8S6AxpuqIrNW3CM8Y97iRpBA=,tag:lsWkpADa9bmAQrsrYppWRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNUR1dVhzZ3Y0R1F5dEJm
            NFpTbTVXSnhsZnY3L2RZcFU0Y0dkTlBzNm4wCkJOYVRCc1lmVFFOTU5ZOWxocGFU
            M0NYa29lOENPZjZSZ0dGNGo2dG5XNVkKLS0tIExnRkowY3BJWHdvOHB4NXk2Wi91
            RVVJZlAzU3I1VHEwazlVdGJ1Vy96TzQKc1O94txfz9CL6+ybcCktTVH3+7GTkP06
            qUVjzFi1J2aAP1vWhBqiBpYlNtjJt1V1YOKd5+ulOlgzcPeUEPKuJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T08:08:19Z"
    mac: ENC[AES256_GCM,data:nz7I+/EqCEY4SJPaHO4MgnftLp1qtbaHqQaS4gndPHZdYmMVtVFI8qxe75lbEMek9TlUatVp2IhyVoDW5gaoedmtdtLMQ91M+y7vX9eASpjnPSAOVgkxL98mQlAu5g2UCffplqlZHA8+vPAty2kvE7PbfiIqkvtz5jhpJQ8yhAw=,iv:Nd/L2AM5OP79fnWqwl7RlqLkvxnnCn0hEcsjiOqEWIg=,tag:MQ6IGbbImqFwZqm54/JOzQ==,type:str]
    version: 3.13.3
