apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: vikunja
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:9LbEhJEo9jfmnWhinw==,iv:YsRzq84JPdf5auXUjz/UUGsIhE9MHwpouvrjZsSXW/o=,tag:XTSSR6AAzpz9ngW7kmjrrQ==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:LG2iJg==,iv:zMN5t3R5Q1PS93ktu2oBZrHYQ+H1H+g2PmCOI6pZhrA=,tag:YLbz7bXcYzxd+17jLbW5Cg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:VCsqiNPS,iv:euIoraeshSoBK2+lA3MtWlVRJ9V8kVQ1xzGHSme73Og=,tag:YrlMx5W2FqCZwf1I/ZsyQQ==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:pBG7TF3W,iv:dCoQWrHkKpTGVFPdFNKzdGjkBtIl9v8YIbggVwpjMgs=,tag:kO2s7ImwMuOh47216OhJ2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUXhWM3daazRidDFJQm9T
            RGZwdEJWSXVVQVZqc295Vmh6TUN5bGlGMmxBCmZYYXd1eGN4c05CdC9ZQTF0UlRS
            WG9tTm5oZGNqbkJZUkRoQjlIU2R2Y2sKLS0tIHhkSC8rRVR4cVgvLzhmNVlBWnRv
            KzRIQzlBaUZTZjF0aUlzVFJ0cU0zZGcKk4ybs25n4dR8SCf5fOkPWV0X4UM+lOMp
            UUWhl6az8lWfB0eLgPKo3geCrMj4yU2w4nqKACnsWPb7CNnoB/ORlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T20:59:45Z"
    mac: ENC[AES256_GCM,data:8xmpKI5U/+3WWZIiw0EATdOYz2D1ddjAhQ7IFqmrQx1pCt/p/r4hh4zVdAgnEj40/UIoM40lUXWOKDq8LbyVdgNZABsbR+e1Qu+VklBa7Zg6jvbHURtOccGs7g8rCfXgdxKw6RJt2vxwa00MHYkk2dzMOMZezG1D6B8xkH/IYAw=,iv:AFr39Pta/C1A9KdTJMUmgsF5yc7G+cj+AarVg5LBZWo=,tag:MDVgdQLxXPbvXpauO0JgKQ==,type:str]
    version: 3.13.3
