apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: authentik
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:ViJ0HBXR3VCg,iv:trModJ0lT8LnQVJae7cVdx4Vn9RzSVlohsUsan+r8Js=,tag:i5GyxUihkWj3JDaFuInXOQ==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:qc/sKA==,iv:ybhixM2M8pXnsfbXao5OrUJfpgFxAZJLylZUcFUbbbA=,tag:vqcC5PN1woHqSrd44HfCqA==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:B+5bsXoI,iv:aLet0C7e784yS0ew7SCVJelA+IYHxHP8UtgtUcqqq4k=,tag:0vx/C6kiBP7zIJj9EsLR3g==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:JnkpRay2,iv:p+lP9xn0Sy7SUHZDvrc7jN4QtoRldkvFsowqZDJlTns=,tag:/iZKnFOU3lbUzFiunrZbmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: immich
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:xuBJB0p5lgvd,iv:G04HVmjrlOJKKyiTMOKnsgzX0Xc6mRbULO/4xwYfcgw=,tag:vHdaSjWDZfGrxHrM0RwJpg==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:RkrSOA==,iv:jb5KpU3cFTAPrElifcBH3BoVZUY+YShLDUr65mREYX0=,tag:ltzT1yqBO7vUB3G9kM8F7Q==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:s4T8psE0,iv:7b+ERCzM4oBMYmMwlQEQ5ZgnGrTICS7EMu1uYarDyGk=,tag:6OajJ5IGe0Fn/Q4GisdUWQ==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:5jO85GDh,iv:zfRX84czFE+WXKeFMdpOI33l2i3BEKaFkuC+VCvy7rE=,tag:5aMD8kjGa0zs7deLc5enEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: media
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:VQ+iXihgTYSF,iv:woTSRTB749P+zzYlJpD3T1gfokzagoWQLzjYhbcy7Ww=,tag:dZCyf873kuSb4LznCJOR2A==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:uZpZiw==,iv:MxSF6RLeWBNVuJ3oddq9C36At+v/dzMrrtexPK79NjM=,tag:+I+6TOW1zZLRycUNRAiEXg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:75CfZCa4,iv:iwOJUtSmBspz/dULVdpgaQ0dBPu5jXcmSePeAOpVmus=,tag:pTIEiXqP3opRnor0F//gjA==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:9lRsNpm2,iv:INTutb8UQLDhAGWj2UvM1lE45EDreO136v7CySa+d5Q=,tag:l0NkJ/1JchCkDVwfC/Uqrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: llm-proxy
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:50hwZbORJjGF,iv:TZreJ8E9NdI/wQpvIudlRXwn6+14rEzkoTQ4BXOnZjI=,tag:Skh+lQhya+fRnL1b1BWfrg==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:HCI7+g==,iv:jTpqr1oInsnjx2iA8rKSO6Kj92vY+SK/EnBm+vJQq/I=,tag:QkNbdntOYfKZC0qJnXDU+A==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:mISWNZMr,iv:kBM5KPrvR6qk1GjfFhIxCVzuGIYz6M2dwQYZNGOm810=,tag:KU1DUhjBTr7zEazjGe8C9A==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:jXZGuuFZ,iv:pIJEuF0cNPlW3rh5Y9TJLk4QfDJxIC8GGtECK7YCOXY=,tag:26evAHfD4vl92nb6C7lB0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: outline
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:58aovy8k+DuS,iv:0wySnkCSqjqTehW+CV42RfQtGZVXAjoDa+8DfSEOjvo=,tag:SNPyBeF7obq42siAPCFmRA==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:N77rWA==,iv:o5gftI3nveHSf32PPBkMoPGE5sIValGH6pJ8NNnXLaU=,tag:r3oncApHoGDQyVz7FO0Psw==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:5l9h8Sva,iv:mJuNISpZPRpFt6bpXBenkZpdbUY4IQkTIkvhbIuCDYo=,tag:Expq46AHPeHIXuc5nyKCFw==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:w+arl49X,iv:hsDA+pcuwO2iYZPyIzWXwlQqeeYIVy6O6K6/GASOWks=,tag:yv6XG88wKwdLzbMKx5P06Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: paperless
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:rECXGl3/YDB/,iv:rqp524Y4DdAXP63t2+Zm7huygVE6SZ+wqDY7Dlhx30w=,tag:VynCJnWNDag2dIYvZpbrJg==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:8G1lQw==,iv:Vk8HLp/o1si9fvqgjEzMkw4PR6bmEHDmLgjiDPFFsV0=,tag:hyXfmb3oVmaLXmu2kbo4mg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:4B0wpJVk,iv:M98L03fo3waZQbO+tgy8OCFA8juNA2KhLQRb9LItitk=,tag:U5ET452ApACP0xaXeAIXKQ==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:sczc98M4,iv:eOuX+wsf8B0PBzH2Ux3zGmSo2Vza3GHAhZAoSfTN0oY=,tag:RMhkg3lQHXZQjpQcnZB7cw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: seafile
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:OIAhc9w4dEU5,iv:kCHGSU15L98NCnTWmpmJqxLLMnSfmQPLa61M3koFXAc=,tag:kfsM8vL0hmHF/K0HYVUpoQ==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:cXsrGw==,iv:6NpIEcDD7nPx7bhPN22JQYIB/Q//uU0H9LbsZ/dP4bU=,tag:IhQwN0P8sxNxPFYHdQNXOg==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:JXbcHfMX,iv:JvFAdyj0yxr2+y6Gpz1QZAspYQk5pYfXHPg8KNr3cgY=,tag:0PUhWHCpUOq5xR4hXyLXoQ==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:+WlmyRvs,iv:tncB2juaC+VDUtkbksYi3RJm3Iz3aVTiAcdYhtgZvDc=,tag:HZ0870OrWmIwkzG6MaGHgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: sftp-backup-credentials
    namespace: vaultwarden
type: Opaque
stringData:
    SFTP_HOST: ENC[AES256_GCM,data:9ES1Pb0xMeNY,iv:gHHF4jnaYSmAWub4hbMG9KDTorABLTs+Lrl6NbhPyXY=,tag:9nuRWGb05emQe9cqBPDChQ==,type:str]
    SFTP_PORT: ENC[AES256_GCM,data:HcpGXQ==,iv:2apNbiRienaNJa+a6XGi6xIsgiT/fPlcn5bTXc9kQE0=,tag:gBhf5PQYJaIlkEZyBRpnZQ==,type:str]
    SFTP_USER: ENC[AES256_GCM,data:qat4YsA1,iv:LBZOknrEW8q9IqNvUl2UHr63EVqQHIyXwOwRrjrl8mY=,tag:MLBHaeB6EPB4d5emPrVQ+g==,type:str]
    SFTP_PASSWORD: ENC[AES256_GCM,data:SfHKcD+k,iv:WIvv64IleVTm/1L3l8oHDQWEzGbVbbMwP/sbrrfQYZo=,tag:esLga4VFlOR7LdlJC8UZlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWVo2Ty9XVW40MWx1WVVO
            WGd5ektxc2c3QkljeW9NeEluOTE4SWxBeWxZClBETVRNbi9EUUpNcVBPL2VJZHlR
            Z01JOGRzcm9NWWVrcHFSS3hMQlRrT28KLS0tIGhmUTJHaEZIbWVXMURoSkFnTUFM
            WlpoNThNNE9tdWptbkFXMzhQNzFMRW8KqzRsMY5rNpkdZWRwrjDj+///eGnZHNE1
            v+GkiH0d5xtrLQ3GzPelDnjpD4nBZfBeBRaZRMokWH04MewDiallMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T22:17:48Z"
    mac: ENC[AES256_GCM,data:MqRlBS6chg+XTw4TNmhS2lQ/kZ3qTwK4ivvFleH367q03cYBXsf9u2brOnJ3z9c59A6fwFVpgTs+J4EIl8hkUqXvPIXrmN24iMzYM4jQpNR3Aapn5Q0Q0I4NqblLXdOUsPYmUQEC+4PRCB8/0Xh2k8kr5Q+hk66t5Axi8hRdIsI=,iv:xMoX9bnvEFlgpQRQJsPQESP7aNuRXEq+F1DPEJ1y+og=,tag:hk7Gel/aSx0uey5Jl3LZnA==,type:str]
    version: 3.13.3
