apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-secrets
    namespace: stirling-pdf
type: Opaque
stringData:
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:bdCQBP0oCfmEvyq6/iixfDz1luLrcgf8jMCVfR6j5+Y=,iv:N9X5+oXwX4UFFyqhPL+6QUBJNghR7W6rGrv0H3FunKM=,tag:p3cobVX+wcDi93EPAUtd4g==,type:str]
    SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:iMzrdIozZpA1KoDanYXBccFcbbUXC5DY7fiubelVegHVrQ5U9lhzusC8Mc8pi3RuNHbIJSFA3WyXD49EA8TQfA==,iv:q4Ak00uDmGWWaMXhQV74QJIIDR0i+F61FV1hXTFapqE=,tag:Kn7eFuJ43E0ItyX1Pn8kJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ejZsODlhNGxkQmxmV0t3
            YWpqVngvN2lyeTFSMVdCRTJ4TURuSU9yRmlZCmRsZXc2c3hhaU9aUmhaa292WWVT
            RndreU9wRlNhSkRhMDNUQ054WUcwSVUKLS0tIDBhMXYwdzNUUGNIaUdHWGJDWmp3
            cFB5c1FSRG5xNUI0TUJLdEIyVGtuNVkKRXsmqK1+0kS476i8GLoJw6vDc80UqbRY
            24ekYe/lkN6prUh2ouyCg70QOgLMRjrDEHrlfY3c+gboLmJKNnBgJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T06:47:20Z"
    mac: ENC[AES256_GCM,data:CeYUqk85fXyrykr1teMydJv03x+wlLhFd+Limv+Lflmr2uK8CWU7o+kThkvuf52Vt3nP2LG8YE9NkxhvLAAPPDIxih8gPKxrj9IUTOMMhZhvPbPaIvi9EKIhkndvqeefw9mpL6OMVSdUHh8IS60r6vBAmkLMFH9cYP+BXa9JzTI=,iv:TXEqnFj8u1/eXpiniFCxivJbep1MKSsmTOyX4EDqsf4=,tag:6LkLr/Ii/wiSjkWjZsScBA==,type:str]
    version: 3.13.2
