apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-secrets
    namespace: stirling-pdf
type: Opaque
stringData:
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:bdCQBP0oCfmEvyq6/iixfDz1luLrcgf8jMCVfR6j5+Y=,iv:N9X5+oXwX4UFFyqhPL+6QUBJNghR7W6rGrv0H3FunKM=,tag:p3cobVX+wcDi93EPAUtd4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ejZsODlhNGxkQmxmV0t3
            YWpqVngvN2lyeTFSMVdCRTJ4TURuSU9yRmlZCmRsZXc2c3hhaU9aUmhaa292WWVT
            RndreU9wRlNhSkRhMDNUQ054WUcwSVUKLS0tIDBhMXYwdzNUUGNIaUdHWGJDWmp3
            cFB5c1FSRG5xNUI0TUJLdEIyVGtuNVkKRXsmqK1+0kS476i8GLoJw6vDc80UqbRY
            24ekYe/lkN6prUh2ouyCg70QOgLMRjrDEHrlfY3c+gboLmJKNnBgJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T16:00:54Z"
    mac: ENC[AES256_GCM,data:/WkTvnX4eeHJTLr7FIMgGd/zkf0SGVslJ6IDonVL4x0zazoQCf9jtli5eNysw4mroEJtrYE6mN29zwmFauvBY9tJWthzuxcW0qIEenC+2pNzNLW6C5BrmMhjXVj/kfBwvlulHOftKAYLlWgXcfx14LNtZl/S1EExIcRg9a+Qr2I=,iv:eBgcBhDvARm43SHpjCTZQMZ3xU0A52CudS/k2b5I4D0=,tag:Ao3ZqEsWtvBtId45NA07Ig==,type:str]
    version: 3.13.2
