apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:cfLwVqPo7SMUARn9nu8n8fk2USP0NHizJH7MPTwTsYaZn1N2ACDCuf0p8hhNoXOkwEXv6Bvz5k2S7Hcxhu3OvA==,iv:On9ihLD/9fstkOLpQuBNdx/ZijbdfrIVnfHwThLxFcA=,tag:ALpFu/7rnStllXZJY7+OrA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:3rfTbCgZZjy2oEdn7Fi9Gj6jTU0pwXRvgiqUTlAQu+p7MsJd9R9XROf9C9XO6iM+gFFvhqZeAh6f5QoJs79OYPUcNPoFYUJJOmd+oZ6QI4Awzot7M8xcDBWNaQStlg+t,iv:KXAOklYvZ2pc2uluaQt8xcdQiTcSZ/7YGmcU0Ypt/rg=,tag:shlLnnIycNeAmx4F91yvxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU2k0SjAvempXWm1LaVhD
            VVd3NDNudmlaT1d2QXYvckJKZElPcW5rVkNrCjZoWXBOZFhOc3h4NFNnN1lsR0xz
            L3VQTUpGQTY3L3hIQ21rVGtJOCs0Y1kKLS0tIDR2QzBJUFl1ZDNWYmhUTG5SSjha
            Q1hPUlp3b1hDblFrZStwSlZhcHZZbTQKMMtFDvYBlvmE1IMvP4JwAmLMdSU6Umxx
            L84kzwoK4zYg2BRfpl+uZzxXHvOV/q7ysdgBxvg7E7pvc1kThXBO/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T17:53:10Z"
    mac: ENC[AES256_GCM,data:UGy7nEzCRI+yInYZA0iXjLZqLnZh6fl2E6iJjjf0Mju645iy1v6eIHvryesbDY8K4KTdHNdjCGpuEg538tCDNds0Peqng/iVrCtEjQvXOSIWgSxz2fG8PhnujcKQh5dGwD5cC9jKxbanVsNtiDB6Rr1Tvd0pfq4ZTNQKPDCdl/U=,iv:4VqRYD4C3wQCU0CjZPsUpeYLpkFxdXQMTltH496E0NM=,tag:msayakPXnIPsMlEI0E/vsg==,type:str]
    version: 3.13.3
