apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:ggBH/LpBx0ANY7uvwSJUrwroxQtjYBaoZWWm4zS/1r/u4t/JPG9OczdXG2Ni+6R4CEagm1s9UyHnLlB7sKB1dQ==,iv:P9eM6oPL2BgyPBf5v1OV4h/iotwpIcbd2ImsLmUljbM=,tag:Ee49+RJGN8vtNbnwnEfrbA==,type:str]
    VIKUNJA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:uDr1e9eyTya9IetbfQ81lmAcCzpG41uXAc2Dy1Lt+eiCCEO4dxWurdtKSgwbWhEKuw2wMtwm3PTxT4reh6IlIzGtolDP39/k6Uvu9+L2VXj/i6jsnKrHaJmTtJJtqEdW,iv:AyozEs6dQb43YTR2uTvQ+15QrLHXytxvaPRkgam+kaA=,tag:XtQERrs4MuoY0+mMgITtCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRFVaanYyYmtFSzloNWNQ
            b0YvYkRwNEhFRjA5NmF2NytmWlNKR3BWS1VJCkh4RTJuc05jK1oxT1kwWTFod0dI
            dDZ5VXowWEVmVFpDODhxNE16dEFnODAKLS0tIGpnZ2VsRndiT1pHdk94VkQ5c1ZM
            OHNJbUpFVlpId1Bic1lQNVByMW5EQjgK37ofslyx+SgHqGvF4GBeiX50PBcICcIF
            7W9itfv76pNZw32+LHW3S83YwRDPQF0TF/ax0eUOSI6pTahr71HSHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x03lwvqa0ped3wgmmrg9yaph6e7ljvs4ztnqkm62wfccwpjm7vjsptkkfl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T11:12:57Z"
    mac: ENC[AES256_GCM,data:J7NnPXKH88tVHc99tmHgFRvgUevxU9OuPwZrqTTsdKudW6MENagCjizdMI0Oo8x09mnBq0Nza+YU7cxUt+/AElQU43g3cT0AR/sPTIeKRBU2/bOlkiB8O1FbmgT69yc0yGcAG+48hUsM5nQls+ZZXpekX1m6XyJ5CGvDycatFRY=,iv:m9q1+y9DsOWZthQDLS+XiLnEqF4Nq4xgpZTn4abUYEo=,tag:qtTUHqoDbxb2xeI5anSVIw==,type:str]
    version: 3.13.3
