apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: coins-inventory-redis
  namespace: coins-inventory
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.4.11
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: coins-inventory-config
      key: REDIS_PASSWORD
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
    service:
      serviceType: ClusterIP
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
