apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: geron
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.21.0
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
