apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-geron
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: platform
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "*"
    helm:
      releaseName: geron
      values: |
        githubConfigUrl: https://github.com/Vasary/geron
        githubConfigSecret: github-runner-auth
        controllerServiceAccount:
          namespace: arc-systems
          name: arc
        minRunners: 0
        maxRunners: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
