apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: geron
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.15.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        fullnameOverride: kube-prometheus-stack
        grafana:
          enabled: false
        alertmanager:
          enabled: true
        prometheus:
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - prometheus.geron.cfv3.org
            paths:
              - /
            pathType: Prefix
          prometheusSpec:
            retention: 14d
            scrapeInterval: 30s
            evaluationInterval: 30s
        kubeEtcd:
          enabled: true
          service:
            enabled: true
            port: 2381
            targetPort: 2381
          serviceMonitor:
            scheme: http
            insecureSkipVerify: true
        kubeControllerManager:
          enabled: true
        kubeScheduler:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
