apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform
  source:
    repoURL: https://helm.mariadb.com/mariadb-operator
    chart: mariadb-operator
    targetRevision: 25.10.3
    helm:
      releaseName: mariadb-operator
      values: |
        clusterName: cluster.vasary.org
        metrics:
          enabled: true
        webhook:
          cert:
            certManager:
              enabled: true
          serviceMonitor:
            enabled: true
        certController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
