apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-smoke
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: geron
  source:
    repoURL: https://github.com/Vasary/geron.git
    targetRevision: master
    path: helm/apps/storage-smoke
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
