apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-seasonvar
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprint
    blueprints.goauthentik.io/instantiate: "true"
data:
  seasonvar.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: vasary-seasonvar-proxy
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_core.group
        id: seasonvar-users-group
        state: present
        identifiers:
          name: seasonvar-users
        attrs:
          name: seasonvar-users
      - model: authentik_core.group
        id: homepage-users-group
        state: present
        identifiers:
          name: homepage-users
        attrs:
          name: homepage-users
      - model: authentik_core.group
        id: frigate-admins-group
        state: present
        identifiers:
          name: frigate-admins
        attrs:
          name: frigate-admins
      - model: authentik_core.group
        id: frigate-viewers-group
        state: present
        identifiers:
          name: frigate-viewers
        attrs:
          name: frigate-viewers
      - model: authentik_providers_proxy.proxyprovider
        id: seasonvar-proxy-provider
        state: present
        identifiers:
          name: seasonvar
        attrs:
          name: seasonvar
          mode: forward_single
          grant_types:
            - authorization_code
          external_host: https://seasonvar.vasary.org
          internal_host: http://seasonvar.media.svc.cluster.vasary.org
          internal_host_ssl_validation: true
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
          redirect_uris:
            - matching_mode: strict
              url: https://seasonvar.vasary.org/outpost.goauthentik.io/callback?X-authentik-auth-callback=true
              redirect_uri_type: authorization
            - matching_mode: strict
              url: https://seasonvar.vasary.org?X-authentik-auth-callback=true
              redirect_uri_type: authorization
      - model: authentik_providers_proxy.proxyprovider
        id: homepage-proxy-provider
        state: present
        identifiers:
          name: homepage
        attrs:
          name: homepage
          mode: forward_single
          grant_types:
            - authorization_code
          external_host: https://home.vasary.org
          internal_host: http://homepage.homepage.svc.cluster.vasary.org
          internal_host_ssl_validation: true
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
          redirect_uris:
            - matching_mode: strict
              url: https://home.vasary.org/outpost.goauthentik.io/callback?X-authentik-auth-callback=true
              redirect_uri_type: authorization
            - matching_mode: strict
              url: https://home.vasary.org?X-authentik-auth-callback=true
              redirect_uri_type: authorization
      - model: authentik_providers_proxy.proxyprovider
        id: frigate-proxy-provider
        state: present
        identifiers:
          name: frigate
        attrs:
          name: frigate
          mode: forward_single
          grant_types:
            - authorization_code
          external_host: https://frigate.vasary.org
          internal_host: http://frigate.media.svc.cluster.vasary.org
          internal_host_ssl_validation: true
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          cookie_domain: vasary.org
          redirect_uris:
            - matching_mode: strict
              url: https://frigate.vasary.org/outpost.goauthentik.io/callback?X-authentik-auth-callback=true
              redirect_uri_type: authorization
            - matching_mode: strict
              url: https://frigate.vasary.org?X-authentik-auth-callback=true
              redirect_uri_type: authorization
      - model: authentik_core.application
        id: seasonvar-application
        state: present
        identifiers:
          slug: seasonvar
        attrs:
          name: Seasonvar
          slug: seasonvar
          provider: !KeyOf seasonvar-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://seasonvar.vasary.org/
          open_in_new_tab: true
      - model: authentik_core.application
        id: homepage-application
        state: present
        identifiers:
          slug: homepage
        attrs:
          name: Homepage
          slug: homepage
          provider: !KeyOf homepage-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://home.vasary.org/
          open_in_new_tab: true
      - model: authentik_core.application
        id: frigate-application
        state: present
        identifiers:
          slug: frigate
        attrs:
          name: Frigate
          slug: frigate
          provider: !KeyOf frigate-proxy-provider
          policy_engine_mode: any
          meta_launch_url: https://frigate.vasary.org/
          open_in_new_tab: true
      - model: authentik_policies.policybinding
        id: seasonvar-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf seasonvar-application
          group: !KeyOf seasonvar-users-group
          order: 0
        attrs:
          target: !KeyOf seasonvar-application
          group: !KeyOf seasonvar-users-group
          order: 0
      - model: authentik_policies.policybinding
        id: homepage-users-policy-binding
        state: present
        identifiers:
          target: !KeyOf homepage-application
          group: !KeyOf homepage-users-group
          order: 0
        attrs:
          target: !KeyOf homepage-application
          group: !KeyOf homepage-users-group
          order: 0
      - model: authentik_policies.policybinding
        id: frigate-admins-policy-binding
        state: present
        identifiers:
          target: !KeyOf frigate-application
          group: !KeyOf frigate-admins-group
          order: 0
        attrs:
          target: !KeyOf frigate-application
          group: !KeyOf frigate-admins-group
          order: 0
      - model: authentik_policies.policybinding
        id: frigate-viewers-policy-binding
        state: present
        identifiers:
          target: !KeyOf frigate-application
          group: !KeyOf frigate-viewers-group
          order: 1
        attrs:
          target: !KeyOf frigate-application
          group: !KeyOf frigate-viewers-group
          order: 1
      - model: authentik_outposts.outpost
        id: authentik-embedded-outpost
        state: present
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          providers:
            - !KeyOf seasonvar-proxy-provider
            - !KeyOf homepage-proxy-provider
            - !KeyOf frigate-proxy-provider
