apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../platform/components/deployment-history-limit
resources:
  - config.yaml
  - storage.yaml
  - workload.yaml
  - routing.yaml
