apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data
  namespace: outline
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
