apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database-local
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  bootstrap:
    initdb:
      database: immich
      owner: immich
  storage:
    storageClass: local-path
    size: 6Gi
  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-database-local
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
