apiVersion: v1
kind: Service
metadata:
  name: cf-tunnel-argocd
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vasary.org
    geron.io/dns-scope: public
spec:
  type: ExternalName
  externalName: cbe0a6d5-be77-4ba3-a152-170629639f9a.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: cf-tunnel-echo
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.vasary.org
    geron.io/dns-scope: public
spec:
  type: ExternalName
  externalName: cbe0a6d5-be77-4ba3-a152-170629639f9a.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: cf-tunnel-prometheus
  namespace: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.vasary.org
    geron.io/dns-scope: public
spec:
  type: ExternalName
  externalName: cbe0a6d5-be77-4ba3-a152-170629639f9a.cfargotunnel.com
