apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-configs
  namespace: stirling-pdf
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
