apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: seafile-ccnet-db
  namespace: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  mariaDbRef:
    name: seafile-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: ccnet_db
  table: "*"
  username: seafile
  host: "%"
  cleanupPolicy: Skip
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: seafile-seafile-db
  namespace: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  mariaDbRef:
    name: seafile-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: seafile_db
  table: "*"
  username: seafile
  host: "%"
  cleanupPolicy: Skip
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: seafile-seahub-db
  namespace: seafile
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  mariaDbRef:
    name: seafile-mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: seahub_db
  table: "*"
  username: seafile
  host: "%"
  cleanupPolicy: Skip
