apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-shared
  namespace: seafile
spec:
  storageClassName: local-path-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
