apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: echo-postgres
  namespace: echo-server
spec:
  instances: 1
  bootstrap:
    initdb:
      database: echo
      owner: echo
  storage:
    storageClass: nfs
    size: 1Gi
