apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: echo-redis
  namespace: echo-server
  annotations:
    opstreelabs.in/redis: "true"
spec:
  redisConfig:
    maxMemoryPercentOfLimit: 80
    dynamicConfig:
      - maxmemory-policy allkeys-lru
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi
