apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      securityContext:
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: whoami
          image: traefik/whoami:v1.11.0
          args:
            - --port=8080
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: echo-postgres-rw.echo-server.svc.cluster.local
            - name: DATABASE_NAME
              value: echo
            - name: DATABASE_USER
              value: echo
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: echo-postgres-app
                  key: password
            - name: REDIS_HOST
              value: echo-redis.echo-server.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: nfs-data
              mountPath: /mnt/nfs
            - name: local-data
              mountPath: /mnt/local
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 64Mi
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: echo-nfs-data
        - name: local-data
          persistentVolumeClaim:
            claimName: echo-local-data
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  selector:
    app.kubernetes.io/name: echo-server
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server
  namespace: echo-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - secretName: echo-geron-tls
      hosts:
        - echo.geron.cfv3.org
  rules:
    - host: echo.geron.cfv3.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-server
                port:
                  name: http
