apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../platform/components/sftp-backup-uploader
resources:
  - database-cluster.yaml
  - database-logical.yaml
  - library.yaml
  - postgres-backup.yaml
