apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  storageClassName: local-path-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
