apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components/sftp-backup-uploader
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - backup.yaml
